INSERT INTO states(id, state_name) VALUES (NEXTVAL('states_seq'), 'GUJARAT');

INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'A', 'GNR', 'Gandhinagar', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'A', 'SKT', 'Sabarkantha', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'A', 'BKT', 'Banaskantha', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'A', 'ARV', 'Aravalli', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'MRB', 'Morbi', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'RJK', 'Rajkot', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'BVN', 'Bhavnagar', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'AHD', 'Ahmedabad', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'BTD', 'Botad', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'B', 'KTC', 'Kachchh', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'C', 'SRT', 'Surat', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'BRC', 'Bharuch', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'VLD', 'Valsad', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'NVR', 'Navsari', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'KHD', 'Kheda', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'AND', 'Anand', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'BRD', 'Vadodara', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'PCM', 'Panchmahal', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'CHU', 'Chhota Udaipur', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'MHS', 'Mahisagara', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'D', 'DHD', 'Dahod', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'JNG', 'Junagadh', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'JMR', 'Jamnagar', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'PBR', 'Porbandar', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'SNR', 'Surendranagar', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'DVD', 'Devbhumi dwarka', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'GRS', 'Gir-Somnath', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'MEH', 'Mehsana', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'PTN', 'Patan', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'E', 'AMR', 'Amreli', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'F', 'DNG', 'The Dangs', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'F', 'NRM', 'Narmada', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'F', 'PNM', 'Panchmahal', (select id from states where state_name = 'GUJARAT'));
INSERT INTO districts(id, branch_code, district_code, district_name, state_id) VALUES (NEXTVAL('districts_seq'), 'F', 'TPI', 'Tapi', (select id from states where state_name = 'GUJARAT'));


/** lang **/
/***gu***/
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_contractor', 'gu', 'ceicedforms', 'જેના માટે ઇલેક્ટ્રિકલ કોન્ટ્રાક્ટર લાઈસન્સ લાગુ થાય છે તેનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'mobile_no_of_applicant', 'gu', 'ceicedforms', 'અરજદારનો મોબાઇલ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'email_id_of_applicant', 'gu', 'ceicedforms', 'અરજદારનો ઇમેઇલ આઈડી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'office_address', 'gu', 'ceicedforms', 'ઓફિસનું સરનામું');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'office_block_no', 'gu', 'ceicedforms', 'ઓફિસ નંબર / બ્લોક નં.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'building_name', 'gu', 'ceicedforms', 'બિલ્ડિંગનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'type_of_organization', 'gu', 'ceicedforms', 'સંસ્થાના પ્રકાર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_org_type', 'gu', 'ceicedforms', 'સંસ્થાના પ્રકાર પસંદ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'partnership_deed', 'gu', 'ceicedforms', 'ભાગીદારી ખત');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_organization', 'gu', 'ceicedforms', 'સંસ્થા ની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_partner', 'gu', 'ceicedforms', 'પાર્ટનરનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob', 'gu', 'ceicedforms', 'જન્મ તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'home_address', 'gu', 'ceicedforms', 'ઘરનું સરનામું');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attachments_documents', 'gu', 'ceicedforms', 'દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'signature_of_partner', 'gu', 'ceicedforms', 'પાર્ટનર ની સહી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob_proof', 'gu', 'ceicedforms', 'જન્મતારીખ ની સાબિતી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_proof', 'gu', 'ceicedforms', 'સરનામા ની સાબિતી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'click_to_add_details', 'gu', 'ceicedforms', 'વિગતો ઉમેરવા માટે ક્લિક કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'add', 'gu', 'ceicedforms', 'ઉમેરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_contractor_license_previously_granted', 'gu', 'ceicedforms', 'શું કોન્ટ્રાક્ટર લાઇસન્સ પહેલાં મંજૂર થયેલ છે?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_number', 'gu', 'ceicedforms', 'કોન્ટ્રાક્ટર લાઈસન્સ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_date_of_issue', 'gu', 'ceicedforms', 'કોન્ટ્રાક્ટર લાઈસન્સ કાઢી આપવાની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'yes', 'gu', 'ceicedforms', 'હા');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'no', 'gu', 'ceicedforms', 'ના');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_holder_details', 'gu', 'ceicedforms', 'પરમિટ ધારકની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_supervisor', 'gu', 'ceicedforms', 'સુપરવાઇઝરનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_no_of_supervisor', 'gu', 'ceicedforms', 'સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_permit_date_of_issue', 'gu', 'ceicedforms', 'સુપરવાઈઝર પરમિટ કાઢી આપવાની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob_supervisor', 'gu', 'ceicedforms', 'સુપરવાઈઝર ની જન્મ તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'age_if_age_is_more_than_70_attach_medical_certificate', 'gu', 'ceicedforms', 'ઉંમર (જો સુપરવાઇઝરની ઉંમર 70 વર્ષથી વધુ હોય તો સિવિલ સર્જનના તબીબી પ્રમાણપત્ર જોડો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document_regarding_supervisor', 'gu', 'ceicedforms', 'સુપરવાઇઝર સંબંધિત દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_address_proof_of_supervisor', 'gu', 'ceicedforms', 'સુપરવાઇઝર ના સરનામાનો પુરાવો જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_medical_certificate_of_civil_surgeon', 'gu', 'ceicedforms', 'સિવિલ સર્જન ના તબીબી પ્રમાણપત્ર જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'last_experience_of_supervisor_with_any_licensed_contractor', 'gu', 'ceicedforms', 'સુપરવાઇઝર નો અન્ય કોઇ લાઇસન્સ કોન્ટ્રાક્ટર સાથે નો છેલો અનુભવ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_name', 'gu', 'ceicedforms', 'કોન્ટ્રેક્ટર નું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_no', 'gu', 'ceicedforms', 'કોન્ટ્રેક્ટર નો લાઈસન્સ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_starting', 'gu', 'ceicedforms', 'પ્રતિ (શરૂઆતની તારીખ)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_leaving', 'gu', 'ceicedforms', 'માટે (છોડવાની તારીખ)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_“i”_verified_by_electrical_inspector_or_representative', 'gu', 'ceicedforms', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_supervisor_signature', 'gu', 'ceicedforms', 'સુપરવાઇઝર સહી જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_signature', 'gu', 'ceicedforms', 'સહી જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_documents_regarding_contractor_license', 'gu', 'ceicedforms', 'સુપરવાઇઝર સંબંધિત દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_instruments', 'gu', 'ceicedforms', 'સાધનોની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'bank_solvency_certificate', 'gu', 'ceicedforms', 'બેન્ક સૉલ્વેન્સી સર્ટિફિકેટ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'invoice_of_instruments', 'gu', 'ceicedforms', 'સાધનોની ઇન્વોઇસ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'owners_declaration', 'gu', 'ceicedforms', 'માલિક નું ડિકલેરેશન');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration_of_supervisor', 'gu', 'ceicedforms', 'સુપરવાઇઝર નું ડિકલેરેશન');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'appointment_letter', 'gu', 'ceicedforms', 'નિમણૂંક પત્ર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_owner_is_not_supervisor', 'gu', 'ceicedforms', '(જો માલિક સુપરવાઇઝર ના હોય તો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'letter_of_declaration', 'gu', 'ceicedforms', 'ડિકલેરેશન પત્ર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_owner_and_supervisor_same_person', 'gu', 'ceicedforms', '(જો માલિક અને સુપરવાઇઝર એક જ વ્યક્તિ હોય તો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'affidavit', 'gu', 'ceicedforms', 'એફિડેવિટ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'download_affidavit_from_below_link', 'gu', 'ceicedforms', 'નીચેની લિંક પરથી એફિડેવિટની લખાણ ડાઉનલોડ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'signature', 'gu', 'ceicedforms', 'હસ્તાક્ષર (માલિક / નિયામક / પાર્ટનર્સ)');
/* MODIFICATION IN CONTRACTOR’S DETAILS */
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'change_correction_name', 'gu', 'ceicedforms', 'શું નામમાં કોઈ ફેરફાર અથવા બદલાવ છે?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_name', 'gu', 'ceicedforms', 'જો હા નામ આપો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_name_change', 'gu', 'ceicedforms', '(જો નામ માં બદલાવ હોય તો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_no', 'gu', 'ceicedforms', 'કોન્ટ્રાક્ટર લાઇસન્સ નં.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_issue_of_license', 'gu', 'ceicedforms', 'લાયસન્સ કાઢી આપ્યાની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_there_is_change_in_address', 'gu', 'ceicedforms', 'સરનામાંમાં કોઈ ફેરફાર છે?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_new_address', 'gu', 'ceicedforms', '(જો "હા" કૃપા કરીને નવા સરનામાં પ્રદાન કરો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_address_change', 'gu', 'ceicedforms', '(સરનામાંમાં ફેરફારના કિસ્સામાં)');
/* MODIFICATION IN PROPRIETOR Or PARTNERS NAME */
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_name_if_any_changes', 'gu', 'ceicedforms', 'કોન્ટ્રાક્ટર નું નામ(જો નામ માં બદલાવ હોય તો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_change_in_partners', 'gu', 'ceicedforms', 'ભાગીદારોમાં ફેરફારના કિસ્સામાં');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_partners', 'gu', 'ceicedforms', 'ભાગીદારોની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_partner', 'gu', 'ceicedforms', 'ભાગીદારનું નામ');
/* CONTRACTOR’S LICENSE RENEWAL */
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'expiry_date_of_license', 'gu', 'ceicedforms', 'લાયસન્સ સમાપ્તિ તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_of_form_“i”_verified_by_authority', 'gu', 'ceicedforms', 'તેના પ્રતિનિધિ દ્વારા માન્ય "ફોર્મ-I" ની નકલ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_supervisor_working_with_firm   ', 'gu', 'ceicedforms', 'પેઢી સાથે કામ કરતા સુપરવાઇઝરની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_joining', 'gu', 'ceicedforms', 'જોડાયા ની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_supervisor_still_working', 'gu', 'ceicedforms', 'ઉપરોક્ત સુપરવાઇઝર હજુ પણ પેઢી સાથે કામ કરે છે?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_“no”_details_of_new_supervisor', 'gu', 'ceicedforms', '(જો "ના" નવા સુપરવાઇઝરની વિગતો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_new_supervisor', 'gu', 'ceicedforms', 'નવા સુપરવાઇઝરની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_new_address', 'gu', 'ceicedforms', '(જો "હા" કૃપા કરીને નવા સરનામાં પ્રદાન કરો)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_change_of_address', 'gu', 'ceicedforms', 'સરનામાંમાં કોઈ ફેરફાર છે?');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_title', 'gu', 'ceicedforms', 'ફોર્મ જે * "ઇલેક્ટ્રિકલ કોન્ટ્રાક્ટરના લાઇસન્સ માટે અરજી"');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_modification_title', 'gu', 'ceicedforms','કોન્ટ્રાક્ટરના વિગતમાં ફેરફાર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'proprietor_partner_name_modification_title', 'gu', 'ceicedforms', 'માલિક અથવા પાર્ટનરનું નામ બદલવું');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_renewal', 'gu', 'ceicedforms', 'કોન્ટ્રાક્ટર્સ લાઇસેંસ રિન્યૂઅલ');

INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'if_temp_address_available', 'gu','ceicedforms', 'જો અસ્થાયી સરનમુ હોય તો');

INSERT INTO locale_message(  id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'Experience', 'gu', 'ceicedforms','અનુભવ');

INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'),'supervisor_permit_no', 'gu', 'ceicedforms','સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'prevExamDateMonthYear', 'gu', 'ceicedforms', 'અગાઉનીપરીક્ષા તારીખ / મહિનો અને વર્ષ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'previous_exam_center', 'gu', 'ceicedforms', 'અગાઉનું પરીક્ષા કેન્દ્ર');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'previous_roll_no', 'gu', 'ceicedforms', 'પહેલાનો પરીક્ષા નો રોલ નં.');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'exam_type', 'gu', 'ceicedforms', 'પરીક્ષાનો પ્રકાર');

INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'passing_year_technical_qualification', 'gu', 'ceicedforms', 'ટેકનિકલ લાયકાત માટે પાસ થવાનો વર્ષ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'technical_qualification_state', 'gu', 'ceicedforms', 'કયા રાજયમાંથી ટેકનિકલ લાયકાત મેળવેલ છે');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'Affidavit To Be Attached If From Other State', 'gu', 'ceicedforms', 'જો ગુજરાતથી ના હોય તો એફિડેવિટ જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'qualification', 'gu', 'ceicedforms', 'લાયકાત');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'technical_qualification', 'gu', 'ceicedforms', 'તકનિકી લાયકાત');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'affidavit_attached_if_from_gu', 'gu', 'ceicedforms', 'જો ગુજરાતથી ના હોય તો એફિડેવિટ જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'wireman_permit_no', 'gu', 'ceicedforms', 'વાયરમેન પરમિટ નં.');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'change_correction_name', 'gu', 'ceicedforms', 'શું નામમાં કોઈ ફેરફાર અથવા બદલાવ છે?');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'is_there_is_change_in_address', 'gu', 'ceicedforms', 'સરનામાંમાં કોઈ ફેરફાર છે?');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'gujarat_state_permit_no', 'gu', 'ceicedforms', 'ગુજરાત રાજ્ય પરમિટ નં.');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'date_of_issue', 'gu', 'ceicedforms', 'કાઢી આપ્યા તારીખ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'qualification_and_present_designation', 'gu', 'ceicedforms', 'લાયકાત અને વર્તમાન હોદ્દો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'permit_no_of_other_state', 'gu', 'ceicedforms', 'અન્ય રાજ્યની પરવાનગી નંબર');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'year_of_passing_exam', 'gu', 'ceicedforms', 'પાસિંગ પરીક્ષા વર્ષ (જો પાસ થયેલ પરીક્ષા)');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'permit_issue_date', 'gu', 'ceicedforms', 'પરમિટ(પરવાનગી) કાઢી આપવાની તારીખ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_original_permit_copy', 'gu', 'ceicedforms', 'મૂળ પરમિટ(પરવાનગી) ની નકલ જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_exemption_certificate_copy', 'gu', 'ceicedforms', 'જો એક્ઝેમ્પ્શન લેવામાં આવેલ હોય તો એક્ઝેમ્પ્શન પ્રમાણપત્ર જોડો.');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_affidavit_if_interstate', 'gu', 'ceicedforms', 'જો ઇન્ટરસ્ટેટ હોય તો એફિડેવિટ જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'name_of_present_org_in_gujarat', 'gu', 'ceicedforms', 'ગુજરાતમાં વર્તમાન સંગઠનનું નામ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'address_of_present_org_in_gujarat', 'gu', 'ceicedforms', 'ગુજરાતમાં વર્તમાન સંગઠનનું સરનામું');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_appointment_letter', 'gu', 'ceicedforms', 'નિમણૂંક પત્ર જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'applying_for_permit_or_exemption_certificate', 'gu', 'ceicedforms', ' પરવાનગી અથવા મુક્તિ પ્રમાણપત્ર માટે અરજી');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'address', 'gu', 'ceicedforms', 'સરનામું');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_signature', 'gu', 'ceicedforms', 'સહી જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'affidavit', 'gu', 'ceicedforms', 'એફિડેવિટ');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'attach_photocopy_of_permit', 'gu', 'ceicedforms', 'પરમિટની ફોટોકોપી જોડો');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'name_applicant', 'gu', 'ceicedforms', 'નામ અરજી કરનાર');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'form_reapeter_title', 'gu', 'ceicedforms', 'રીપીટર ઉમેદવાર ઇલેક્ટ્રિકલ સુપરવાઇઝર અથવા વાયરમેન માટે પરીક્ષામાં પ્રવેશ માટે અરજી');
INSERT INTO locale_message VALUES (NEXTVAL('locale_seq'), 'wireman_or_supervisor_permit_no', 'gu', 'ceicedforms', 'વાયરમેન અને સુપરવાઇઝર પરમિટ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'personal_detail', 'gu', 'ceicedforms', '<h2>અંગત વિગતો<h2>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'surname', 'gu', 'ceicedforms', 'અટક');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'first_name', 'gu', 'ceicedforms', 'પ્રથમ નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'father_husband_middle_name', 'gu', 'ceicedforms', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'origional_dob', 'gu', 'ceicedforms', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_documents', 'gu', 'ceicedforms', 'દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'school_leaving_certificate', 'gu', 'ceicedforms', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'age', 'gu', 'ceicedforms', 'ઉંમર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'gender', 'gu', 'ceicedforms', 'જાતિ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'male', 'gu', 'ceicedforms', 'પુરૂષ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'female', 'gu', 'ceicedforms', 'સ્ત્રી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permanent_address', 'gu', 'ceicedforms', 'કાયમી સરનામુ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'house_flat_block_no', 'gu', 'ceicedforms', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'building_appartment_name', 'gu', 'ceicedforms', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'taluka_name', 'gu', 'ceicedforms', 'તાલુકાનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'district_name', 'gu', 'ceicedforms', 'જિલ્લાનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'state', 'gu', 'ceicedforms', 'રાજ્ય');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'pincode', 'gu', 'ceicedforms', 'પીન કોડ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_proof_or_valid_proof', 'gu', 'ceicedforms', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવાકોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'temporary_address', 'gu', 'ceicedforms', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'upload_photograph', 'gu', 'ceicedforms', 'ફોટો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'upload_signature', 'gu', 'ceicedforms', 'હસ્તાક્ષર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaratin_electrical_wireman_in_gujarat_state', 'gu', 'ceicedforms', 'ગુજરાત રાજ્યમાં ઇલેક્ટ્રિકલ વાયરમેન પરમિટની મુક્તિ માટેની ડિકલેરેશન');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_examination_form_declation', 'gu', 'ceicedforms', 'હું અહીંથી જાહેર કરું છું કે ઉપર જણાવેલી વિશેષતા મારા જ્ઞાનના પ્રમાણે શ્રેષ્ઠ અને સાચી છે');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'school_leaving_certificate', 'gu', 'ceicedforms', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_file', 'gu', 'ceicedforms', 'ફાઇલ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_state', 'gu', 'ceicedforms', 'રાજ્ય પસંદ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contact_detail_title', 'gu', 'ceicedforms', 'સંપર્ક ની વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'mobile_no', 'gu', 'ceicedforms', 'મોબાઇલ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'alternate_mobile_no', 'gu', 'ceicedforms', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'email_applicant', 'gu', 'ceicedforms', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'examination_requirements', 'gu', 'ceicedforms', '<h2>પરીક્ષાની જરૂરીયાતો</h2>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'eligiblity_appearing_exam', 'gu', 'ceicedforms', 'પરીક્ષામાં ઉપસ્થિત થવાની લાયકાત');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_organization', 'gu', 'ceicedforms', 'સંસ્થાનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'electrical_contractor_no', 'gu', 'ceicedforms', 'ઇલેક્ટ્રિકલ કોન્ટ્રાક્ટર લાઈસન્સ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'from_start_date', 'gu', 'ceicedforms', 'પ્રતિ (શરૂઆતની તારીખ)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'to_leaving_date', 'gu', 'ceicedforms', 'માટે (છોડવાની તારીખ)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_name', 'gu', 'ceicedforms', 'સુપરવાઇઝરનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_permit_no.', 'gu', 'ceicedforms', 'સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document_after_filling_above_information', 'gu', 'ceicedforms', 'ઉપરની માહિતી ભરીને દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_k', 'gu', 'ceicedforms', 'ફોર્મ "કે" (એક પીડીએફમાં "કે")');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_of_form_i_verified_inspector', 'gu', 'ceicedforms', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના) ની નકલ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'click_enter_past_present_experience', 'gu', 'ceicedforms', 'ભૂતકાળ અને વર્તમાન અનુભવ વિગતો દાખલ કરવા માટે ઉમેરવા માટે ક્લિક કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'preferred_examination_center', 'gu', 'ceicedforms', 'મનપસંદ પરીક્ષા કેન્દ્ર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'preferred_mode_of_language', 'gu', 'ceicedforms', 'ભાષાની મનપસંદ રીત');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document', 'gu', 'ceicedforms', 'દસ્તાવેજ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'serial_no', 'gu', 'ceicedforms', 'અનુક્રમ નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_past_present_experience', 'gu', 'ceicedforms', 'ભૂતકાળ અને વર્તમાન અનુભવ વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_exam_center', 'gu', 'ceicedforms', 'પરીક્ષા કેન્દ્ર પસંદ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_language_mode', 'gu', 'ceicedforms', 'ભૂતકાળ અને વર્તમાન અનુભવ વિગતો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_examinatin_title', 'gu', 'ceicedforms', '<strong> ફોર્મ A1 * </ strong> વાયરમેન માટે પરીક્ષામાં અરજી ફોર્મ પ્રવેશ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_passport_photo', 'gu', 'ceicedforms', 'એક પાસપોર્ટ કદ ફોટોગ્રાફ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_scan_signature', 'gu', 'ceicedforms', 'સહીની એક સ્કેન નકલ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'fields_mandatory', 'gu', 'ceicedforms', 'ક્ષેત્રો ફરજિયાત છે');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_district', 'gu', 'ceicedforms', 'જિલ્લા પસંદ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_a2', 'gu', 'ceicedforms', 'ફોર્મ A2');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_reapeter_title', 'gu', 'ceicedforms', 'રીપીટર ઉમેદવાર ઇલેક્ટ્રિક સુપરવાઇઝર અથવા વાયરમેન માટે પરીક્ષામાં પ્રવેશ માટે અરજી');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form', 'gu', 'ceicedforms', 'ફોર્મ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_title', 'gu', 'ceicedforms', 'ઇલેક્ટ્રિકલ વાયરમેન પરીક્ષાની મુક્તિ માટે અરજી ફોર્મ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_modification_title', 'gu', 'ceicedforms', 'વાયરમેન વિગતોમાં ફેરફાર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_renewal_title', 'gu', 'ceicedforms', 'ઇન્ટરસ્ટેટ નવીકરણ વાયરમેન');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'interstate_permit_title', 'gu', 'ceicedforms', 'ફોર્મ L * “ગુજરાત રાજયમાં ઇલેક્ટ્રિકલ સુપરવાઇઝર / વાયરમેન પરમિટ માટે ઇન્ટરસ્ટેટ માન્યતા માટેની અરજી.“');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'duplicate_permit_title', 'gu', 'ceicedforms', 'વાયરમેન અને સુપરવાઇઝર ડુપ્લિકેટ પરમિટ વિગતો ફોર્મ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_affidavit_if_not_from_gu', 'gu', 'ceicedforms', 'જો ગુજરાતથી નહીં તો એફિડેવિટ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_declationtion', 'gu', 'ceicedforms', 'ગુજરાત રાજ્યમાં વિદ્યુત સુપરવાઇઝર પરમિટ્સની મુક્તિ માટે ઘોષણા.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_declationtion2', 'gu', 'ceicedforms', 'હું આ મુજબ જાહેર કરું છું કે હું ગુજરાત રાજ્ય અથવા અન્ય કોઇ રાજ્ય દ્વારા જારી કરાયેલા કોઈપણ સુપરવાઇઝર પરમિટ ધરાવી રહ્યો છું.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'myselft_form_liable_information', 'gu', 'ceicedforms', 'ખોટી માહિતી માટે હું પોતે કાર્યવાહી માટે જવાબદાર છું.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'repeater_declairation', 'gu', 'ceicedforms', 'હું અહીંથી જાહેર કરું છું કે ઉપરોક્ત particuler મારા જ્ઞાનના શ્રેષ્ઠ અને સાચું છે.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration', 'gu', 'ceicedforms', 'હું અહીંથી ગંભીરતાપૂર્વક જાહેર કરું છું કે ઉપર જણાવેલ વિગતો મારા જ્ઞાનના શ્રેષ્ઠ અને સાચા છે અને ઉપર જણાવેલી સિવાય કોઈપણ રાજ્યના અન્ય કોઈ પરમિટ નથી.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_owners_signature', 'gu', 'ceicedforms', 'માલિકોની હસ્તાક્ષર જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name', 'gu', 'ceicedforms', 'નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_leaving_of_old_supervisor', 'gu', 'ceicedforms', 'જૂની સુપરવાઇઝર છોડવાની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'technical_contractors_name', 'gu', 'ceicedforms', 'ટેકનિકલ ઠેકેદારનું નામ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_employer', 'gu', 'ceicedforms', 'એમ્પ્લોયરની વિગતો');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'if_temp_address_available', 'gu','ceicedforms', 'જો અસ્થાયી સરનમુ હોય તો');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'date_issue_wireman_permit', 'gu','ceicedforms', 'વાયરમેન પરમિટ(પરવાનગી) કાઢી આપવાની તારીખ');
INSERT INTO locale_message(  id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'experience', 'gu', 'ceicedforms','અનુભવ');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'s_no', 'gu','ceicedforms', 'અનુ. નં.');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'name_of_university', 'gu','ceicedforms', 'યુનિવર્સિટીનું નામ');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'year_of_passing', 'gu','ceicedforms', 'પાસિંગનું વર્ષ');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'name_of_institute', 'gu','ceicedforms', 'સંસ્થા અને કોલેજનું નામ');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'district_state_college', 'gu','ceicedforms', 'જિલ્લાનું નામ અથવા કોલેજનું રાજ્ય');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'declaration_exemption_supervisor_GU', 'gu','ceicedforms', 'ગુજરાત રાજ્યમાં ઇલેક્ટ્રિકલ સુપરવાઇઝર પરમિટની મુક્તિ માટેની ડિકલેરેશન');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'myself_liable_prosecution_info', 'gu','ceicedforms', 'ખોટી માહિતી માટે હું પોતે કાર્યવાહી માટે જવાબદાર છું.');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'exemption_certificate', 'gu','ceicedforms', 'મુક્તિ પ્રમાણપત્ર');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'marksheet', 'gu','ceicedforms', 'માર્કપત્રક');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'repeater_declairation', 'gu', 'ceicedforms', 'હું અહીંથી જાહેર કરું છું કે ઉપર જણાવેલ ચોક્કસ માહિતી મારા જ્ઞાનના પ્રમાણે યોગ્ય અને સાચી છે');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'wireman_or_supervisor_permit', 'gu','ceicedforms', 'વાયરમેન અથવા સુપરવાઇઝર પરમિટ');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'declaration_holding_supervisor_gu_state', 'gu','ceicedforms', 'હું આ મુજબ જાહેર કરું છું કે હું ગુજરાત રાજ્ય અથવા અન્ય કોઇ રાજ્ય દ્વારા જારી કોઈ સુપરવાઇઝર પરમિટ નથી રાખતો.');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'attach_wireman_permit', 'gu','ceicedforms', 'વાયરમેન પરમિટ જોડો');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'superwiser_examination_title', 'gu','ceicedforms', '<strong> ફોર્મ A1 * </ strong> ઇલેક્ટ્રિકલ સુપરવાઇઝર માટે પરીક્ષા માટે અરજી ફોર્મ પ્રવેશ.');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'supervisor_modification_title', 'gu','ceicedforms', 'સુપરવાઇઝરની વિગતોમાં ફેરફાર');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'superwiser_renewal_title', 'gu','ceicedforms', 'ઇન્ટરસ્ટેટ નવીકરણ સુપરવાઇઝર');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'supervisor_exemption_title', 'gu','ceicedforms', 'ઇલેક્ટ્રિકલ સુપરવાઇઝર એક્સએમએમમાંથી મુક્તિ માટે અરજી પત્ર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'affidavit_to_be_if_from', 'gu', 'ceicedforms','જો અન્ય રાજ્ય થી હોય તો એફિડેવિટ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'other_state', 'gu', 'ceicedforms','અન્ય રાજ્ય');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_permenant_address_proof_belong_state', 'gu', 'ceicedforms', 'જો ગુજરાત રાજ્ય માંથી ના હોય તો  તેના રાજ્ય નું કાયમી સરનામું ની સાબિતી જોડો ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_not_from_gu', 'gu', 'ceicedforms', 'જો ગુજરાતથી ના હોય');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_marksheet_all_sem', 'gu', 'ceicedforms', 'જો અન્ય રાજ્યથી હોય તો બધા સત્રના માર્કશીટ જોડો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'enrolment_no', 'gu', 'ceicedforms', 'નોંધણી નંબર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_a3', 'gu', 'ceicedforms', 'ફોર્મ A3');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'writing_depar_person', 'gu', 'ceicedforms', 'વાયરિંગ વિભાગના વ્યક્તિઓ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permitno', 'gu', 'ceicedforms', 'પરમિટ નં.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'jobstatus', 'gu', 'ceicedforms', 'જોબ સ્થિતિ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'joiningdate', 'gu', 'ceicedforms', 'જોડાયા તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'leavingdate', 'gu', 'ceicedforms', 'છોડવાની તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'designation', 'gu', 'ceicedforms', 'હોદ્દો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date', 'gu', 'ceicedforms', 'તારીખ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'inactive', 'gu', 'ceicedforms', 'નિષ્ક્રિય');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'USER_ALREADY_EXISTS', 'gu', 'ceicedforms', 'User already exists');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'invalid_token', 'gu', 'ceicedforms', 'Invailid token');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'server_not_responding', 'gu', 'ceicedforms', 'Server not responding');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'error', 'gu', 'ceicedforms', 'Error');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_i', 'gu', 'ceicedforms', 'ફોર્મ “I”');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_allform_in_k_pdf', 'gu', 'ceicedforms', 'attach all form “K” in one PDF');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'registration_certificate', 'gu', 'ceicedforms', 'નોંધણી પ્રમાણપત્ર');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'memorandum', 'gu', 'ceicedforms', 'મેમોરેન્ડમ');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_form_i_verified_by_competent_authority', 'gu', 'ceicedforms', 'સક્ષમ અધિકારી દ્વારા ચકાસાયેલ <span class="noteText" style="font-size: 15px;">ફોર્મ I </span> કૉપિ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'all_pages', 'gu', 'ceicedforms', 'બધા પેજીસ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'final_submit', 'gu', 'ceicedforms', 'અંતિમ સબમિટ કરો');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'previous', 'gu', 'ceicedforms', 'અગાઉના');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'apprenticeship_certificate', 'en', 'ceicedforms', 'એપ્રોનિટીશીપ સર્ટિફિકેટ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'experience_certificate', 'en', 'ceicedforms', 'અનુભવ સર્ટિફિકેટ');


/***en***/
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name', 'en', 'ceicedforms', 'Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_examinatin_title', 'en', 'ceicedforms', '<strong>Form A1*</strong> ''Application Form Admission To Examination For Wireman'' ');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'personal_detail', 'en', 'ceicedforms', '<h2>PERSONAL DETAILS</h2>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'surname', 'en', 'ceicedforms', 'Surname');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'first_name', 'en', 'ceicedforms', 'First Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'father_husband_middle_name', 'en', 'ceicedforms', 'Father / Husband Or Middle Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'origional_dob', 'en', 'ceicedforms', 'Date of Birth (As per school leaving certificate)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_documents', 'en', 'ceicedforms', 'Attach Documents');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'school_leaving_certificate', 'en', 'ceicedforms', 'School leaving certificate or matriculation certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'school_leaving_certificate_matriculation_certificate', 'en', 'ceicedforms', 'School leaving certificate or matriculation certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'age', 'en', 'ceicedforms', 'Age');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_file', 'en', 'ceicedforms', 'Attach file');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'gender', 'en', 'ceicedforms', 'Gender');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'male', 'en', 'ceicedforms', 'Male');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'female', 'en', 'ceicedforms', 'Female');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permanent_address', 'en', 'ceicedforms', 'PERMANENT ADDRESS');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'house_flat_block_no', 'en', 'ceicedforms', 'House No. / Flat No. / Block No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'building_appartment_name', 'en', 'ceicedforms', 'Building Name / Apartment Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'taluka_name', 'en', 'ceicedforms', 'Taluka Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'district_name', 'en', 'ceicedforms', 'District Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_district', 'en', 'ceicedforms', 'Select District');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'state', 'en', 'ceicedforms', 'State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_state', 'en', 'ceicedforms', 'Select State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'pincode', 'en', 'ceicedforms', 'Pincode');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document', 'en', 'ceicedforms', 'Attach Document');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'temporary_address', 'en', 'ceicedforms', 'TEMPORARY ADDRESS');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'mobile_no', 'en', 'ceicedforms', 'Mobile No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'alternate_mobile_no', 'en', 'ceicedforms', 'Alternate Mobile No. (Optional)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'email_applicant', 'en', 'ceicedforms', 'Email Id of The Applicant');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'email_validation_message', 'en', 'ceicedforms', 'This field should be an e-mail address in the format ''user@example.com''');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'examination_requirements', 'en', 'ceicedforms', '<h2>EXAMINATION REQUIREMENTS</h2>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'eligiblity_appearing_exam', 'en', 'ceicedforms', 'Eligiblity For Appearing In Exam');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'empty_message_exam_eligiblity', 'en', 'ceicedforms', 'Select wireman exam eligiblity');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_past_present_experience', 'en', 'ceicedforms', 'Details of Past & Present Experience');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'click_enter_past_present_experience', 'en', 'ceicedforms', 'Click to add to enter Past & Present Experience details');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'add', 'en', 'ceicedforms', 'Add');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'preferred_examination_center', 'en', 'ceicedforms', 'Preferred Examination Center');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_exam_center', 'en', 'ceicedforms', 'Select examination center');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'preferred_mode_of_language', 'en', 'ceicedforms', 'Preferred Mode of Language');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_language_mode', 'en', 'ceicedforms', 'Select language mode');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'upload_photograph', 'en', 'ceicedforms', 'Upload Photograph');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_passport_photo', 'en', 'ceicedforms', 'Attach a passport size photograph');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_scan_signature', 'en', 'ceicedforms', 'Attach a scan copy of signature');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_examination_form_declation', 'en', 'ceicedforms', 'I hereby declare that the particular stated above are correct and true to the best my knowledge.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'fields_mandatory', 'en', 'ceicedforms', 'Fields are Mandatory');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'save', 'en', 'ceicedforms', 'Save');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'submit', 'en', 'ceicedforms', 'Submit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contact_detail_title', 'en', 'ceicedforms', 'CONTACT DETAILS');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_a3', 'en', 'ceicedforms', 'Form A3');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_title', 'en', 'ceicedforms', 'Application Form For Exemption From Electrical Wireman Exam.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'qualification', 'en', 'ceicedforms', 'QUALIFICATION');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'technical_qualification', 'en', 'ceicedforms', 'Technical Qualification');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_technical_qualification', 'en', 'ceicedforms', 'Select Technical Qualification');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'passing_year_technical_qualification', 'en', 'ceicedforms', 'Year of Passing for Technical Qualification');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'technical_qualification_state', 'en', 'ceicedforms', 'Technical Qualification from which State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'affidavit_attached_if_from_gu', 'en', 'ceicedforms', 'Affidavit To Be Attached If From Other State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'other_state', 'en', 'ceicedforms', 'Other State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_affidavit_if_not_from_gu', 'en', 'ceicedforms', 'Attach affidavit if not from Gujarat');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_declationtion', 'en', 'ceicedforms', 'Declaration for exemption of electrical Supervisor permits in Gujarat state.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_exemption_declationtion2', 'en', 'ceicedforms', 'I hereby declare that i am holding any Supervisor permit issued by Gujarat state or any other state.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'myselft_form_liable_information', 'en', 'ceicedforms', 'I myself is liable for prosecution for false information.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_modification_title', 'en', 'ceicedforms', 'Modification In Wireman Details');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'change_correction_name', 'en', 'ceicedforms', 'Is there any change or correction in name ?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'yes', 'en', 'ceicedforms', 'Yes');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_permit_no', 'en', 'ceicedforms', 'Wireman Permit No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_name', 'en', 'ceicedforms', '(if “yes“ please provide name)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_there_is_change_in_address', 'en', 'ceicedforms', 'Is there any change in address ?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_address', 'en', 'ceicedforms', '(if “yes“ please provide address)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_renewal_title', 'en', 'ceicedforms', 'Interstate Renewal Wireman');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_applicant', 'en', 'ceicedforms', 'Name of applicant');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'gujarat_state_permit_no', 'en', 'ceicedforms', 'Gujarat state Permit No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_issue', 'en', 'ceicedforms', 'Date of Issue');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'superwiser_examination_title', 'en', 'ceicedforms', '<strong>Form A1* </strong> Application Form Admission To Examination For Electrical Supervisor.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_temp_address_available', 'en', 'ceicedforms', 'If the address is as above please dont fill <span class=''noteText''> Temporary or correspondence address</span>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'exam_type', 'en', 'ceicedforms', 'Exam Type');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'experience', 'en', 'ceicedforms', 'Experience');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_applied', 'en', 'ceicedforms', 'Application Applied');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_pending', 'en', 'ceicedforms', 'Application Pending');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_approved', 'en', 'ceicedforms', 'Application Approved');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_contractor', 'en', 'ceicedforms', 'Name of which an electrical contractor’s license is applied for');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'mobile_no_of_applicant', 'en', 'ceicedforms', 'Mobile no. of the applicant');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'email_id_of_applicant', 'en', 'ceicedforms', 'Email-id of the applicant');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'office_address', 'en', 'ceicedforms', 'OFFICE ADDRESS');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'office_block_no', 'en', 'ceicedforms', 'Office no. / Block no.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'building_name', 'en', 'ceicedforms', 'Building name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'type_of_organization', 'en', 'ceicedforms', 'Type of organization');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'partnership_deed', 'en', 'ceicedforms', 'Partnership deed');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_organization', 'en', 'ceicedforms', 'Details of organization');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'click_to_add_details', 'en', 'ceicedforms', 'Click to add details');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_contractor_license_previously_granted', 'en', 'ceicedforms', 'Is contractor license previously granted ?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'no', 'en', 'ceicedforms', 'No');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_number', 'en', 'ceicedforms', 'Contractor license number');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_date_of_issue', 'en', 'ceicedforms', 'Date of issue (contractor license)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_holder_details', 'en', 'ceicedforms', 'Details of permit holder on the strength of whose permit the contractor license is applied for.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_supervisor', 'en', 'ceicedforms', 'Name of supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_no_of_supervisor', 'en', 'ceicedforms', 'Permit no. of supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_permit_date_of_issue', 'en', 'ceicedforms', 'Date of issue of supervisor permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob_supervisor', 'en', 'ceicedforms', 'Date of birth of supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'age_if_age_is_more_than_70_attach_medical_certificate', 'en', 'ceicedforms', 'Age (if age of supervisor is more than 70 years attach medical certificate of civil surgeon)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document_regarding_supervisor', 'en', 'ceicedforms', 'Attach document regarding supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_address_proof_of_supervisor', 'en', 'ceicedforms', 'Attach address proof of supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_medical_certificate_of_civil_surgeon', 'en', 'ceicedforms', 'Attach medical certificate of civil surgeon');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'last_experience_of_supervisor_with_any_licensed_contractor', 'en', 'ceicedforms', 'Last experience of supervisor with any licensed contractor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_title', 'en', 'ceicedforms', 'Form J* “Application for an Electrical Contractor’s License”');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_name', 'en', 'ceicedforms', 'Name of contractor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_no', 'en', 'ceicedforms', 'Contractor License No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_starting', 'en', 'ceicedforms', 'From (Date of starting)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_leaving', 'en', 'ceicedforms', 'To (Date of leaving)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_“i”_verified_by_electrical_inspector_or_representative', 'en', 'ceicedforms', 'Form “I” verified by electrical inspector or his representative');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_supervisor_signature', 'en', 'ceicedforms', 'Attach supervisor signature');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_signature', 'en', 'ceicedforms', 'Attach signature');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_documents_regarding_contractor_license', 'en', 'ceicedforms', 'Attach documents regarding contractor license');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'bank_solvency_certificate', 'en', 'ceicedforms', 'Bank solvency certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_instruments', 'en', 'ceicedforms', 'Details of instruments (please fill the editable PDF & attach it back)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'invoice_of_instruments', 'en', 'ceicedforms', 'Invoice of instruments');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'owners_declaration', 'en', 'ceicedforms', 'Owners declaration');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration_of_supervisor', 'en', 'ceicedforms', 'Declaration of supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'appointment_letter', 'en', 'ceicedforms', 'Appointment letter');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_owner_is_not_supervisor', 'en', 'ceicedforms', '(if owner is not supervisor)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'affidavit', 'en', 'ceicedforms', 'Affidavit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'letter_of_declaration', 'en', 'ceicedforms', 'Letter of declaration');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_owner_and_supervisor_same_person', 'en', 'ceicedforms', '(if the owner & supervisor are the same person)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'serial_no', 'en', 'ceicedforms', 'Sn No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_partner', 'en', 'ceicedforms', 'Name of Partner');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob', 'en', 'ceicedforms', 'Date of Birth');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'home_address', 'en', 'ceicedforms', 'Home Address');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attachments_documents', 'en', 'ceicedforms', 'Attachments documents');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_proof_or_valid_proof', 'en', 'ceicedforms', 'Attach electricty bill for address proof or any <span class=''noteText'' style=''font-size: 15px;''> Govt. valid ID </span> proof');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 's_no', 'en', 'ceicedforms', 'Serial No');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_firm', 'en', 'ceicedforms', 'Name of firm');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'from_start_date', 'en', 'ceicedforms', 'From (Date of starting)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'to_leaving_date', 'en', 'ceicedforms', 'To (Date of Leaving)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_name', 'en', 'ceicedforms', 'Supervisor Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_permit_no', 'en', 'ceicedforms', 'Supervisor Permit No');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'delete', 'en', 'ceicedforms', 'delete');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_modification_title', 'en', 'ceicedforms', 'MODIFICATION IN CONTRACTOR’S DETAILS');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_name_change', 'en', 'ceicedforms', '(In case of name change)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_issue_of_license', 'en', 'ceicedforms', 'Date of issue of license');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_yes_provide_new_address', 'en', 'ceicedforms', '(if “yes” please provide new address)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_address_change', 'en', 'ceicedforms', '(In case of address change)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'superwiser_renewal_title', 'en', 'ceicedforms', 'Interstate Renewal Supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_modification_title', 'en', 'ceicedforms', 'Modification In Supervisor Details');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'supervisor_exemption_title', 'en', 'ceicedforms', 'Application Form For Exemption From Electrical SupervisorExam.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'enrolment_no', 'en', 'ceicedforms', 'Enrolment no.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_university', 'en', 'ceicedforms', 'Name of University');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'year_of_passing', 'en', 'ceicedforms', 'Year of Passing');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'affidavit_to_be_if_from', 'en', 'ceicedforms', 'Affidavit To Be Attached If From');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_permenant_address_proof_belong_state', 'en', 'ceicedforms', 'Attach Permanent address proof of the state from which you belong');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_institute', 'en', 'ceicedforms', 'Name of The Institute & College');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'district_state_college', 'en', 'ceicedforms', 'District Or State Name of College');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_marksheet_all_sem', 'en', 'ceicedforms', 'Attach marksheet of all sem if from');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'writing_depar_person', 'en', 'ceicedforms', 'Wiring department Persons');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'proprietor_partner_name_modification_title', 'en', 'ceicedforms', 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'case_of_change_in_partners', 'en', 'ceicedforms', '(in case of change in partners)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_partners', 'en', 'ceicedforms', 'Details of Partners (Change in partners)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'select_org_type', 'en', 'ceicedforms', 'Select organization type');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'contractor_license_renewal', 'en', 'ceicedforms', 'CONTRACTOR’S LICENSE RENEWAL');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'expiry_date_of_license', 'en', 'ceicedforms', 'Expiry date of license');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_of_form_“i”_verified_by_authority', 'en', 'ceicedforms', 'Copy of <span class=''noteText'' style=''font-size: 15px;''>Form “I”</span> verified by authority or his representative');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_supervisor_working_with_firm', 'en', 'ceicedforms', 'Details of supervisor working with firm');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_joining', 'en', 'ceicedforms', 'Date of joining');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'is_supervisor_still_working', 'en', 'ceicedforms', 'Is the above mentioned supervisor still working with the firm ?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_“no”_details_of_new_supervisor', 'en', 'ceicedforms', '(if “no” Details of new supervisor)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_of_leaving_of_old_supervisor', 'en', 'ceicedforms', 'Date of leaving of old supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_new_supervisor', 'en', 'ceicedforms', 'Details of new supervisor');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_owners_signature', 'en', 'ceicedforms', 'Attach Owners Signature');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_change_of_address', 'en', 'ceicedforms', '(Address Proof Only To Be Given If Change of Address)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'signature_of_partner', 'en', 'ceicedforms', 'Signature of partner');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dob_proof', 'en', 'ceicedforms', 'Date of birth proof');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_proof', 'en', 'ceicedforms', 'Address proof');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration_exemption_supervisor_GU', 'en', 'ceicedforms', 'Declaration for exemption of electrical Supervisor permits in Gujarat state.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration_holding_supervisor_gu_state', 'en', 'ceicedforms', 'I hereby declare that i am holding any Supervisor permit issued by Gujarat state or any other state.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'myself_liable_prosecution_info', 'en', 'ceicedforms', 'I myself is liable for prosecution for false information.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_proof_if_change', 'en', 'ceicedforms', '(Address Proof Only To Be Given If Change of Address)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'national_apprenticeship_certificate', 'en', 'ceicedforms', 'NATIONAL APPRENTICESHIP CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'national_trade_certificate', 'en', 'ceicedforms', 'NATIONAL TRADE CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'electrical_service_technician_certificate', 'en', 'ceicedforms', 'ELECTRICAL SERVICE TECHNICIAN CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'electrical_installation_wiring_and_jointing_certificate', 'en', 'ceicedforms', 'ELECTRICAL INSTALLATION,WIRING AND JOINTING CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'all_semester_marks_sheet', 'en', 'ceicedforms', 'ALL SEMESTER MARKS SHEET');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'certificate', 'en', 'ceicedforms', 'CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'marks_sheet_of_last_year', 'en', 'ceicedforms', 'MARKS SHEET OF LAST YEAR');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'diploma_certificate', 'en', 'ceicedforms', 'DIPLOMA CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'degree_certificate', 'en', 'ceicedforms', 'DEGREE CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'national_trade_certificate_ele', 'en', 'ceicedforms', 'NATIONAL TRADE CERTIFICATE (ELE)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_k', 'en', 'ceicedforms', 'FORM ''K''');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'upload_signature', 'en', 'ceicedforms', 'Upload Signature');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_form_i_verified_by_competent_authority', 'en', 'ceicedforms', 'COPY OF <span class="noteText" style="font-size: 15px;display: inline;"> FORM I </span> VERIFIED BY COMPETENT AUTHORITY');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'national_apprenticeship_certificate_ele', 'en', 'ceicedforms', 'NATIONAL APPRENTICESHIP CERTIFICATE (ELE)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'technical_examination_board_certicate', 'en', 'ceicedforms', 'TECHNICAL EXAMINATION BOARD CERTICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'print_preview', 'en', 'ceicedforms', 'Print Preview');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'interstate_permit_title', 'en', 'ceicedforms', 'Form L* “Application For Interstate recognition for Electrical Supervisor / Wireman Permit in Gujarat State.”');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'qualification_and_present_designation', 'en', 'ceicedforms', 'QUALIFICATION & PRESENT DESIGNATION');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_no_of_other_state', 'en', 'ceicedforms', 'Permit No. of Other State');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'year_of_passing_exam', 'en', 'ceicedforms', 'Year of Passing Exam <span class=''noteText'' style=''font-size: 15px;display: inline;''>(if passed exam)</span>');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permit_issue_date', 'en', 'ceicedforms', 'Date of issue of Permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_present_org_in_gujarat', 'en', 'ceicedforms', 'Name of Present Organization In Gujarat');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address_of_present_org_in_gujarat', 'en', 'ceicedforms', 'Address of Present Organization In Gujarat');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaration', 'en', 'ceicedforms', 'I hereby do solemnly declare that the particulars stated above are correct and true to best of my knowledge and i am not having any other permit of any state except stated above.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_appointment_letter', 'en', 'ceicedforms', 'Attach Appointment Letter');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_affidavit_if_interstate', 'en', 'ceicedforms', 'Attach affidavit if Interstate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_exemption_certificate_copy', 'en', 'ceicedforms', 'Attach Exemption Certificate Copy If taken Exemption');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_original_permit_copy', 'en', 'ceicedforms', 'Attach Original Permit Copy');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'duplicate_permit_title', 'en', 'ceicedforms', 'Wireman & Supervisor Duplicate Permit Details Form');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'applying_for_permit_or_exemption_certificate', 'en', 'ceicedforms', 'Applying for supervisor / wireman permit or exemption certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'exemption_certificate', 'en', 'ceicedforms', 'Exemption certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_or_supervisor_permit', 'en', 'ceicedforms', 'Wireman or Supervisor Permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'marksheet', 'en', 'ceicedforms', 'Marksheet');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'wireman_or_supervisor_permit_no', 'en', 'ceicedforms', 'Wireman Or Supervisor Permit No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_photocopy_of_permit', 'en', 'ceicedforms', 'Attach Photocopy of Permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'address', 'en', 'ceicedforms', 'Address');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attachment_deleted', 'en', 'ceicedforms', 'Attachment deleted');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'success', 'en', 'ceicedforms', 'Success');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_a2', 'en', 'ceicedforms', 'Form A2');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_reapeter_title', 'en', 'ceicedforms', 'Application For Admission To Examination For Repeater Candidate Electrical Supervisor Or Wireman');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'repeater_declairation', 'en', 'ceicedforms', 'I hereby declare that the particuler stated above are correct and true to the best my knowledge.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'previous_roll_no', 'en', 'ceicedforms', 'Previous Exam Roll No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'previous_exam_center', 'en', 'ceicedforms', 'Previous Exam Centre');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'prevExamDateMonthYear', 'en', 'ceicedforms', 'Previous Exam Date/Month & Year');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'permitno', 'en', 'ceicedforms', 'Permit No.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'jobstatus', 'en', 'ceicedforms', 'Job Status');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'joiningdate', 'en', 'ceicedforms', 'Joining date');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'leavingdate', 'en', 'ceicedforms', 'Leaving date');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'designation', 'en', 'ceicedforms', 'Designation');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date', 'en', 'ceicedforms', 'Date');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'details_of_employer', 'en', 'ceicedforms', 'Details of employer');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_deleted', 'en', 'ceicedforms', 'Application deleted');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'sure_delete_application', 'en', 'ceicedforms', 'You want to delete this application?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'sure', 'en', 'ceicedforms', 'Are you sure?');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_organization', 'en', 'ceicedforms', 'Name of organization');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'electrical_contractor_no', 'en', 'ceicedforms', 'Electrical Contractor License Number');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'copy_of_form_i_verified_inspector', 'en', 'ceicedforms', 'Copy of Form ''I'' verified by electrical inspector or his representative(All Pages)');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'declaratin_electrical_wireman_in_gujarat_state', 'en', 'ceicedforms', 'Declaratin for exam of electrical wireman in Gujarat state.');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_document_after_filling_above_information', 'en', 'ceicedforms', 'Attach Document After Filling Above Information');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'welcome_application_portal', 'en', 'header', 'Welcome to CEICED Application Portal');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'search', 'en', 'header', 'Search');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'my_profile', 'en', 'header', 'My Profile');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'change_password', 'en', 'header', 'Change Password');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'logout', 'en', 'header', 'Logout');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'home', 'en', 'dashboard', 'Home');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'create_application', 'en', 'dashboard', 'Create Application');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_status', 'en', 'dashboard', 'Application Status');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'need_help', 'en', 'dashboard', 'Need Help');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'message', 'en', 'dashboard', 'Message');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'profile', 'en', 'dashboard', 'Profile');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'dashboard', 'en', 'dashboard', 'Dashboard');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'applicant_name', 'en', 'dashboard', 'Applicant Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_submit_date', 'en', 'dashboard', 'Application Submit Date');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'service_name', 'en', 'dashboard', 'Service Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_status', 'en', 'dashboard', 'Form Status');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'actions', 'en', 'dashboard', 'Actions');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_type', 'en', 'dashboard', 'Application Type');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'service_name', 'en', 'dashboard', 'Service Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'applicant_name', 'en', 'dashboard', 'Applicant Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_name', 'en', 'dashboard', 'Application Name');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'application_submit_date', 'en', 'dashboard', 'Application Submit Date');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_status', 'en', 'dashboard', 'Form Status');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'actions', 'en', 'dashboard', 'Actions');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'error', 'en', 'response', 'Error');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'SERVER_SIDE_ERROR', 'en', 'response', 'Server Side Error');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'server_not_responding', 'en', 'response', 'Server Not Responding');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form', 'en', 'ceicedforms', 'Form');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'date_issue_wireman_permit', 'en', 'ceicedforms', 'Date of Issue of wireman Permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'technical_contractors_name', 'en', 'ceicedforms', 'Technical Contractor’s Name');
INSERT INTO locale_message(id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'),'attach_wireman_permit', 'en','ceicedforms', 'Attach Wireman permit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'if_not_from_gu', 'en', 'ceicedforms', 'If not from Gujarat');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'USER_ALREADY_EXISTS', 'en', 'ceicedforms', 'User already exists');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'invalid_token', 'en', 'ceicedforms', 'Invailid token');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'server_not_responding', 'en', 'ceicedforms', 'Server not responding');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'error', 'en', 'ceicedforms', 'Error');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'inactive', 'en', 'ceicedforms', 'Inactive');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'attach_allform_in_k_pdf', 'en', 'ceicedforms', 'attach all form “K” in one PDF');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'form_i', 'en', 'ceicedforms', 'Form “I”');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'registration_certificate', 'en', 'ceicedforms', 'Registration certificate');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'memorandum', 'en', 'ceicedforms', 'Memorandum');

INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'all_pages', 'en', 'ceicedforms', 'ALL PAGES');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'apprenticeship_certificate', 'en', 'ceicedforms', 'APPRENTICESHIP CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'experience_certificate', 'en', 'ceicedforms', 'EXPERIENCE CERTIFICATE');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'final_submit', 'en', 'ceicedforms', 'Final Submit');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'previous', 'en', 'ceicedforms', 'Previous');

/*09-02-2018*/
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'exam_roll_number', 'en', 'ceicedforms', 'Exam Roll Number');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'name_of_the_local_agent', 'en', 'operating_Escalator_installed_before_commencement_mapping', 'Name of the local agent');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'Details_of_entire_staff_employed', 'en', 'Modification_Agency_Form', 'Staff Details Change Request');
INSERT INTO locale_message (id, key, lang, screen, value) VALUES (NEXTVAL('locale_seq'), 'Details_of_entire_staff_employed', 'gu', 'Modification_Agency_Form', 'સ્ટાફ વિગતો બદલો વિનંતી');
