/*FINAL Query
==========
*/
select count(key) as keycount,key,screen,array_to_string(array_agg(id), ',') as ids from locale_message where lang='en' group by key,screen having count(key) > 1 ;
select count(key) as keycount,key,screen,array_to_string(array_agg(id), ',') as ids from locale_message where lang='gu' group by key,screen having count(key) > 1 ;
/*delete query
===============
 */
delete from locale_message where id in('2106','3599','3618');

CREATE TABLE public.tempData
(
  id bigint NOT NULL,
  key character varying(255),
  lang character varying(255),
  screen character varying(255),
  fieldname character varying(255),
  value character varying(255),
  CONSTRAINT tempdata_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public."tempData"
  OWNER TO postgres
DELETE  FROM "tempData";
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (1, NULL, NULL, 'WireManExemption', 'PERSONAL DETAILS', 'અંગત વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (2, NULL, NULL, 'WireManExemption', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (3, NULL, NULL, 'WireManExemption', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (4, NULL, NULL, 'WireManExemption', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (5, NULL, NULL, 'WireManExemption', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (6, NULL, NULL, 'WireManExemption', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (7, NULL, NULL, 'WireManExemption', 'School leaving certificate or matriculation certificate', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (8, NULL, NULL, 'WireManExemption', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (9, NULL, NULL, 'WireManExemption', 'Gender', 'જાતિ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (10, NULL, NULL, 'WireManExemption', 'Male', 'પુરૂષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (11, NULL, NULL, 'WireManExemption', 'Female', 'સ્ત્રી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (12, NULL, NULL, 'WireManExemption', 'PERMANENT ADDRESS', 'કાયમી સરનામુ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (13, NULL, NULL, 'WireManExemption', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (14, NULL, NULL, 'WireManExemption', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (15, NULL, NULL, 'WireManExemption', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (16, NULL, NULL, 'WireManExemption', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (17, NULL, NULL, 'WireManExemption', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (18, NULL, NULL, 'WireManExemption', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (19, NULL, NULL, 'WireManExemption', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (20, NULL, NULL, 'WireManExemption', 'TEMPORARY ADDRESS (If the address is as above please don''t fill Temporary or correspondance address)', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (21, NULL, NULL, 'WireManExemption', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (22, NULL, NULL, 'WireManExemption', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (23, NULL, NULL, 'WireManExemption', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (24, NULL, NULL, 'WireManExemption', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (25, NULL, NULL, 'WireManExemption', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (26, NULL, NULL, 'WireManExemption', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (27, NULL, NULL, 'WireManExemption', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (28, NULL, NULL, 'WireManExemption', 'CONTACT DETAILS', 'સંપર્ક ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (29, NULL, NULL, 'WireManExemption', 'Mobile No.', 'મોબાઇલ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (30, NULL, NULL, 'WireManExemption', 'Alternate Mobile No. (Optional)', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (31, NULL, NULL, 'WireManExemption', 'Email Id Of The Applicant', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (32, NULL, NULL, 'WireManExemption', 'Qualification', 'લાયકાત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (33, NULL, NULL, 'WireManExemption', 'Technical Qualification', 'તકનિકી લાયકાત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (34, NULL, NULL, 'WireManExemption', 'Attach certificate of EST (Electrical Service Technician)', 'ઈ.એસ.ટી(ઇલેક્ટ્રિકલ સર્વિસ ટેક્નિશ્યન) નો પ્રમાણપત્ર જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (35, NULL, NULL, 'WireManExemption', 'Year Of Passing For Technical Qualification', 'ટેકનિકલ લાયકાત માટે પાસ થવાનો વર્ષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (36, NULL, NULL, 'WireManExemption', 'Technical Qualification From Which State', 'કયા રાજયમાંથી ટેકનિકલ લાયકાત મેળવેલ છે');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (37, NULL, NULL, 'WireManExemption', 'Affidavit To Be Attached If From Other State', 'જો ગુજરાતથી ના હોય તો એફિડેવિટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (38, NULL, NULL, 'WireManExemption', 'Attach affidavit if not from Gujarat (Stamp Paper Of 20 Rs.)', 'જો ગુજરાત રાજયમાંથી ન હોય તો એફિડેવિટ જોડો (20 રૂપિયાના સ્ટેમ્પ પેપર)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (39, NULL, NULL, 'WireManExemption', 'Upload Photograph', 'ફોટો અપલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (40, NULL, NULL, 'WireManExemption', 'Upload Signature', 'હસ્તાક્ષર અપલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (41, NULL, NULL, 'WireManExemption', 'Attach a pasport size photograph', 'પાસપોર્ટ સાઈઝ નો ફોટોગ્રાફ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (42, NULL, NULL, 'WireManExemption', 'Attach a scan copy of signature', 'સહીની સ્કેન નકલ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (43, NULL, NULL, 'WireManExemption', 'Declaration for exemption of electrical wireman permits in Gujarat state', 'ગુજરાત રાજ્યમાં ઇલેક્ટ્રિકલ વાયરમેન પરમિટની મુક્તિ માટેની ડિકલેરેશન');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (44, NULL, NULL, 'WireManExemption', 'I hereby declare that i am not holding any wireman permit issued by Gujarat state or any other state.', 'હું આ મુજબ જાહેર કરું છું કે હું ગુજરાત રાજ્ય અથવા અન્ય કોઇ રાજ્ય દ્વારા જારી કોઈ વાયરમેન પરમિટ નથી રાખતો.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (45, NULL, NULL, 'WireManExemption', 'I myself is liable for prosecution for false information.', 'ખોટી માહિતી માટે હું પોતે કાર્યવાહી માટે જવાબદાર છું.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (46, NULL, NULL, 'Wireman Examination', 'PERSONAL DETAILS', 'અંગત વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (47, NULL, NULL, 'Wireman Examination', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (48, NULL, NULL, 'Wireman Examination', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (49, NULL, NULL, 'Wireman Examination', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (50, NULL, NULL, 'Wireman Examination', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (51, NULL, NULL, 'Wireman Examination', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (52, NULL, NULL, 'Wireman Examination', 'School leaving certificate or matriculation certificate', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (53, NULL, NULL, 'Wireman Examination', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (54, NULL, NULL, 'Wireman Examination', 'Gender', 'જાતિ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (55, NULL, NULL, 'Wireman Examination', 'Male', 'પુરૂષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (56, NULL, NULL, 'Wireman Examination', 'Female', 'સ્ત્રી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (57, NULL, NULL, 'Wireman Examination', 'PERMANENT ADDRESS', 'કાયમી સરનામુ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (58, NULL, NULL, 'Wireman Examination', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (59, NULL, NULL, 'Wireman Examination', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (60, NULL, NULL, 'Wireman Examination', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (61, NULL, NULL, 'Wireman Examination', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (62, NULL, NULL, 'Wireman Examination', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (63, NULL, NULL, 'Wireman Examination', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (64, NULL, NULL, 'Wireman Examination', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (65, NULL, NULL, 'Wireman Examination', 'TEMPORARY ADDRESS (If the address is as above please don''t fill Temporary or correspondance address)', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (66, NULL, NULL, 'Wireman Examination', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (67, NULL, NULL, 'Wireman Examination', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (68, NULL, NULL, 'Wireman Examination', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (69, NULL, NULL, 'Wireman Examination', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (70, NULL, NULL, 'Wireman Examination', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (71, NULL, NULL, 'Wireman Examination', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (72, NULL, NULL, 'Wireman Examination', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (73, NULL, NULL, 'Wireman Examination', 'CONTACT DETAILS', 'સંપર્ક ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (74, NULL, NULL, 'Wireman Examination', 'Mobile No.', 'મોબાઇલ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (75, NULL, NULL, 'Wireman Examination', 'Alternate Mobile No. (Optional)', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (76, NULL, NULL, 'Wireman Examination', 'Email Id Of The Applicant', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (77, NULL, NULL, 'Wireman Examination', 'EXAMINATION REQUIREMENTS', 'પરીક્ષાની જરૂરીયાતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (78, NULL, NULL, 'Wireman Examination', 'Eligibility For Appearing In Exam', 'પરીક્ષામાં ઉપસ્થિત થવાની લાયકાત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (79, NULL, NULL, 'Wireman Examination', 'Name of organization', 'સંસ્થાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (80, NULL, NULL, 'Wireman Examination', 'Electrical Contractor License Number', 'ઇલેક્ટ્રિકલ કોન્ટ્રાક્ટર લાઈસન્સ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (81, NULL, NULL, 'Wireman Examination', 'From (Date of starting)', 'પ્રતિ (શરૂઆતની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (82, NULL, NULL, 'Wireman Examination', 'To (Date of leaving)', 'માટે (છોડવાની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (83, NULL, NULL, 'Wireman Examination', 'Supervisor Name', 'સુપરવાઇઝરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (84, NULL, NULL, 'Wireman Examination', 'Supervisor Permit No.', 'સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (85, NULL, NULL, 'Wireman Examination', 'Attach Document After Filling Above Information', 'ઉપરની માહિતી ભરીને દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (86, NULL, NULL, 'Wireman Examination', 'Form "K" ("K" in one PDF)', 'ફોર્મ "કે" (એક પીડીએફમાં "કે")');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (87, NULL, NULL, 'Wireman Examination', 'Copy of Form "I" verified by electrical inspector or his representative(All Pages)', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના) ની નકલ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (88, NULL, NULL, 'Wireman Examination', 'Click to add to enter Past & Present Experience details', 'ભૂતકાળ અને વર્તમાન અનુભવ વિગતો દાખલ કરવા માટે ઉમેરવા માટે ક્લિક કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (89, NULL, NULL, 'Wireman Examination', 'Preferred Examination Centre', 'મનપસંદ પરીક્ષા કેન્દ્ર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (90, NULL, NULL, 'Wireman Examination', 'Preferred Mode Of Language', 'ભાષાની મનપસંદ રીત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (91, NULL, NULL, 'Wireman Examination', 'Photo', 'ફોટો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (92, NULL, NULL, 'Wireman Examination', 'Signature', 'હસ્તાક્ષર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (93, NULL, NULL, 'Wireman Examination', 'Declaratin for exam of electrical wireman in Gujarat state.', 'ગુજરાત રાજ્યમાં ઇલેક્ટ્રિકલ વાયરમેન પરમિટની મુક્તિ માટેની ડિકલેરેશન');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (94, NULL, NULL, 'Wireman Examination', 'I hereby declare that the particular stated above are correct and true to the best of my knowledge', 'હું અહીંથી જાહેર કરું છું કે ઉપર જણાવેલી વિશેષતા મારા જ્ઞાનના પ્રમાણે શ્રેષ્ઠ અને સાચી છે');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (95, NULL, NULL, 'Supervisor Exemption', 'PERSONAL DETAILS', 'અંગત વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (96, NULL, NULL, 'Supervisor Exemption', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (97, NULL, NULL, 'Supervisor Exemption', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (98, NULL, NULL, 'Supervisor Exemption', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (99, NULL, NULL, 'Supervisor Exemption', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (100, NULL, NULL, 'Supervisor Exemption', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (197, NULL, NULL, 'Supervisor Examination', 'Preferred Examination Centre', 'મનપસંદ પરીક્ષા કેન્દ્ર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (101, NULL, NULL, 'Supervisor Exemption', 'School leaving certificate or matriculation certificate', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (102, NULL, NULL, 'Supervisor Exemption', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (103, NULL, NULL, 'Supervisor Exemption', 'Gender', 'જાતિ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (104, NULL, NULL, 'Supervisor Exemption', 'Male', 'પુરૂષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (105, NULL, NULL, 'Supervisor Exemption', 'Female', 'સ્ત્રી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (106, NULL, NULL, 'Supervisor Exemption', 'PERMANENT ADDRESS', 'કાયમી સરનામુ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (107, NULL, NULL, 'Supervisor Exemption', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (108, NULL, NULL, 'Supervisor Exemption', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (109, NULL, NULL, 'Supervisor Exemption', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (110, NULL, NULL, 'Supervisor Exemption', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (111, NULL, NULL, 'Supervisor Exemption', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (112, NULL, NULL, 'Supervisor Exemption', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (113, NULL, NULL, 'Supervisor Exemption', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (114, NULL, NULL, 'Supervisor Exemption', 'TEMPORARY ADDRESS (If the address is as above please don''t fill Temporary or correspondance address)', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (115, NULL, NULL, 'Supervisor Exemption', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (116, NULL, NULL, 'Supervisor Exemption', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (117, NULL, NULL, 'Supervisor Exemption', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (118, NULL, NULL, 'Supervisor Exemption', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (119, NULL, NULL, 'Supervisor Exemption', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (120, NULL, NULL, 'Supervisor Exemption', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (121, NULL, NULL, 'Supervisor Exemption', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (122, NULL, NULL, 'Supervisor Exemption', 'CONTACT DETAILS', 'સંપર્ક ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (123, NULL, NULL, 'Supervisor Exemption', 'Mobile No.', 'મોબાઇલ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (124, NULL, NULL, 'Supervisor Exemption', 'Alternate Mobile No. (Optional)', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (125, NULL, NULL, 'Supervisor Exemption', 'Email Id Of The Applicant', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (126, NULL, NULL, 'Supervisor Exemption', 'Qualification', 'લાયકાત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (127, NULL, NULL, 'Supervisor Exemption', 'Technical Qualification', 'તકનિકી લાયકાત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (128, NULL, NULL, 'Supervisor Exemption', 'Enrolment no.', 'નોંધણી નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (129, NULL, NULL, 'Supervisor Exemption', 'National apprenticeship certificate (ELE)', 'રાષ્ટ્રીય ઉમેદવારી પ્રમાણપત્ર (ઇ.એલ.ઇ.)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (130, NULL, NULL, 'Supervisor Exemption', 'National trade certificate (ELE)', 'રાષ્ટ્રીય વેપાર પ્રમાણપત્ર (ઇ.એલ.ઇ.)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (131, NULL, NULL, 'Supervisor Exemption', 'Experience certificate for 1 year', '1 વર્ષ માટે અનુભવનું પ્રમાણપત્ર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (132, NULL, NULL, 'Supervisor Exemption', 'Form "K"', '"કે" ફોર્મ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (133, NULL, NULL, 'Supervisor Exemption', 'Copy of Form "I" verified by electrical inspector or his representative(All Pages)', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના) ની નકલ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (134, NULL, NULL, 'Supervisor Exemption', 'Name Of The Institute & College', 'સંસ્થા અને કોલેજનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (135, NULL, NULL, 'Supervisor Exemption', 'Name Of District Or State Of College', 'જિલ્લાનું નામ અથવા કોલેજનું રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (136, NULL, NULL, 'Supervisor Exemption', 'Attach marksheet of all sem if from Other state', 'જો અન્ય રાજ્યથી હોય તો બધા સત્રના માર્કશીટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (137, NULL, NULL, 'Supervisor Exemption', 'Name Of University', 'યુનિવર્સિટીનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (138, NULL, NULL, 'Supervisor Exemption', 'Year Of Passing', 'પાસિંગનું વર્ષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (139, NULL, NULL, 'Supervisor Exemption', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (140, NULL, NULL, 'Supervisor Exemption', 'Affidavit To Be Attached If From Other State', 'જો અન્ય રાજ્ય થી હોય તો એફિડેવિટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (141, NULL, NULL, 'Supervisor Exemption', 'Attach affidavit if not from Gujarat', 'જો ગુજરાતથી ના હોય તો એફિડેવિટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (142, NULL, NULL, 'Supervisor Exemption', 'Attach Permanent address proof of the state from which you belong if not from Gujarat', 'જો ગુજરાત રાજ્ય માંથી ના હોય તો તેના રાજ્ય નું કાયમી સરનામું ની સાબિતી જોડો ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (143, NULL, NULL, 'Supervisor Exemption', 'Upload Photograph', 'ફોટો અપલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (144, NULL, NULL, 'Supervisor Exemption', 'Upload Signature', 'હસ્તાક્ષર અપલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (145, NULL, NULL, 'Supervisor Exemption', 'Attach a pasport size photograph', 'પાસપોર્ટ સાઈઝ નો ફોટોગ્રાફ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (146, NULL, NULL, 'Supervisor Exemption', 'Attach a scan copy of signature', 'સહીની સ્કેન નકલ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (147, NULL, NULL, 'Supervisor Exemption', 'Declaration for exemption of electrical supervsior permits in Gujarat state', 'ગુજરાત રાજ્યમાં ઇલેક્ટ્રિકલ સુપરવાઇઝર પરમિટની મુક્તિ માટેની ડિકલેરેશન');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (198, NULL, NULL, 'Supervisor Examination', 'Preferred Mode Of Language', 'ભાષાની મનપસંદ રીત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (199, NULL, NULL, 'Supervisor Examination', 'Photo', 'ફોટો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (200, NULL, NULL, 'Supervisor Examination', 'Signature', 'હસ્તાક્ષર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (148, NULL, NULL, 'Supervisor Exemption', 'I hereby declare that i am not holding any supervisor permit issued by Gujarat state or any other state.', 'હું આ મુજબ જાહેર કરું છું કે હું ગુજરાત રાજ્ય અથવા અન્ય કોઇ રાજ્ય દ્વારા જારી કોઈ સુપરવાઇઝર પરમિટ નથી રાખતો.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (149, NULL, NULL, 'Supervisor Exemption', 'I myself is liable for prosecution for false information.', 'ખોટી માહિતી માટે હું પોતે કાર્યવાહી માટે જવાબદાર છું.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (150, NULL, NULL, 'Supervisor Examination', 'PERSONAL DETAILS', 'અંગત વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (151, NULL, NULL, 'Supervisor Examination', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (152, NULL, NULL, 'Supervisor Examination', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (153, NULL, NULL, 'Supervisor Examination', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (154, NULL, NULL, 'Supervisor Examination', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (155, NULL, NULL, 'Supervisor Examination', 'School leaving certificate or matriculation certificate', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (156, NULL, NULL, 'Supervisor Examination', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (157, NULL, NULL, 'Supervisor Examination', 'Gender', 'જાતિ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (158, NULL, NULL, 'Supervisor Examination', 'Male', 'પુરૂષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (159, NULL, NULL, 'Supervisor Examination', 'Female', 'સ્ત્રી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (160, NULL, NULL, 'Supervisor Examination', 'Exam Type', 'પરીક્ષાનો પ્રકાર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (161, NULL, NULL, 'Supervisor Examination', 'PERMANENT ADDRESS', 'કાયમી સરનામુ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (162, NULL, NULL, 'Supervisor Examination', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (163, NULL, NULL, 'Supervisor Examination', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (164, NULL, NULL, 'Supervisor Examination', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (165, NULL, NULL, 'Supervisor Examination', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (166, NULL, NULL, 'Supervisor Examination', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (167, NULL, NULL, 'Supervisor Examination', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (168, NULL, NULL, 'Supervisor Examination', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (169, NULL, NULL, 'Supervisor Examination', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (170, NULL, NULL, 'Supervisor Examination', 'TEMPORARY ADDRESS (If the address is as above please don''t fill Temporary or correspondance address)', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (171, NULL, NULL, 'Supervisor Examination', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (172, NULL, NULL, 'Supervisor Examination', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (173, NULL, NULL, 'Supervisor Examination', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (174, NULL, NULL, 'Supervisor Examination', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (175, NULL, NULL, 'Supervisor Examination', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (176, NULL, NULL, 'Supervisor Examination', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (177, NULL, NULL, 'Supervisor Examination', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (178, NULL, NULL, 'Supervisor Examination', 'CONTACT DETAILS', 'સંપર્ક ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (179, NULL, NULL, 'Supervisor Examination', 'Mobile No.', 'મોબાઇલ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (180, NULL, NULL, 'Supervisor Examination', 'Alternate Mobile No. (Optional)', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (181, NULL, NULL, 'Supervisor Examination', 'Email Id Of The Applicant', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (182, NULL, NULL, 'Supervisor Examination', 'EXAMINATION REQUIREMENTS', 'પરીક્ષાની જરૂરીયાતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (183, NULL, NULL, 'Supervisor Examination', 'Wireman Permit No.', 'વાયરમેન પરમિટ(પરવાનગી) નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (184, NULL, NULL, 'Supervisor Examination', 'Attach Wireman permit', 'વાયરમેન પરમિટ(પરવાનગી) જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (185, NULL, NULL, 'Supervisor Examination', 'Date Of Issue Of Wireman Permit', 'વાયરમેન પરમિટ(પરવાનગી) કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (186, NULL, NULL, 'Supervisor Examination', 'Experience', 'અનુભવ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (187, NULL, NULL, 'Supervisor Examination', 'Details Of Past & Present Experience', 'ભૂતકાળ અને વર્તમાન અનુભવની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (188, NULL, NULL, 'Supervisor Examination', 'Name of firm', 'કંપનીનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (189, NULL, NULL, 'Supervisor Examination', 'From (Date of starting)', 'પ્રતિ (શરૂઆતની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (190, NULL, NULL, 'Supervisor Examination', 'To (Date of leaving)', 'માટે (છોડવાની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (191, NULL, NULL, 'Supervisor Examination', 'Supervisor Name', 'સુપરવાઇઝરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (192, NULL, NULL, 'Supervisor Examination', 'Supervisor Permit No.', 'સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (193, NULL, NULL, 'Supervisor Examination', 'Attach Document After Filling Above Information', 'ઉપરની માહિતી ભરીને દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (194, NULL, NULL, 'Supervisor Examination', 'Form "K" ("K" in one PDF)', 'ફોર્મ "કે" (એક પીડીએફમાં "કે")');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (195, NULL, NULL, 'Supervisor Examination', 'Copy of Form "I" verified by electrical inspector or his representative(All Pages)', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના) ની નકલ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (196, NULL, NULL, 'Supervisor Examination', 'Click to add to enter Past & Present Experience details', 'ભૂતકાળ અને વર્તમાન અનુભવ વિગતો દાખલ કરવા માટે ઉમેરવા માટે ક્લિક કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (201, NULL, NULL, 'Supervisor Examination', 'I hereby declare that the particular stated above are correct and true to the best of my knowledge', 'હું અહીંથી જાહેર કરું છું કે ઉપર જણાવેલી વિશેષતા મારા જ્ઞાનના પ્રમાણે શ્રેષ્ઠ અને સાચી છે');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (202, NULL, NULL, 'Modification In Supervisor', 'Supervisor Permit No.', 'સુપરવાઇઝર પરમિટ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (203, NULL, NULL, 'Modification In Supervisor', 'Is there any change or correction in name ?', 'શું નામમાં કોઈ ફેરફાર અથવા બદલાવ છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (204, NULL, NULL, 'Modification In Supervisor', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (205, NULL, NULL, 'Modification In Supervisor', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (206, NULL, NULL, 'Modification In Supervisor', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (207, NULL, NULL, 'Modification In Supervisor', 'Is there any change in address ?', 'સરનામાંમાં કોઈ ફેરફાર છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (208, NULL, NULL, 'Modification In Supervisor', 'House No. / Flat No. / Block No.', 'ઘર નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (209, NULL, NULL, 'Modification In Supervisor', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (210, NULL, NULL, 'Modification In Supervisor', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (211, NULL, NULL, 'Modification In Supervisor', 'District name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (212, NULL, NULL, 'Modification In Supervisor', 'Taluka name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (213, NULL, NULL, 'Modification In Supervisor', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (214, NULL, NULL, 'Modification In Supervisor', 'Attach electricty bill for address pfroof or
any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ જોડો અથવા કોઇ સરકાર માન્ય ઓળખ ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (215, NULL, NULL, 'Modification In Wireman', 'Wireman Permit No.', 'વાયરમેન પરમિટ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (216, NULL, NULL, 'Modification In Wireman', 'Is there any change or correction in name ?', 'શું નામમાં કોઈ ફેરફાર અથવા બદલાવ છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (217, NULL, NULL, 'Modification In Wireman', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (218, NULL, NULL, 'Modification In Wireman', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (219, NULL, NULL, 'Modification In Wireman', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (220, NULL, NULL, 'Modification In Wireman', 'Is there any change in address ?', 'સરનામાંમાં કોઈ ફેરફાર છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (221, NULL, NULL, 'Modification In Wireman', 'House No. / Flat No. / Block No.', 'ઘર નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (222, NULL, NULL, 'Modification In Wireman', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (223, NULL, NULL, 'Modification In Wireman', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (224, NULL, NULL, 'Modification In Wireman', 'District name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (225, NULL, NULL, 'Modification In Wireman', 'Taluka name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (226, NULL, NULL, 'Modification In Wireman', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (227, NULL, NULL, 'Modification In Wireman', 'Attach electricty bill for address pfroof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ જોડો અથવા કોઇ સરકાર માન્ય ઓળખ ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (228, NULL, NULL, 'Contractor License', 'PERSONAL DETAILS', 'વ્યક્તિગત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (229, NULL, NULL, 'Contractor License', 'Name of which an Electrical Contractor License is applied for', 'જેના માટે ઇલેક્ટ્રિકલ કોન્ટ્રાક્ટર લાઈસન્સ લાગુ થાય છે તેનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (230, NULL, NULL, 'Contractor License', 'Mobile No. of the applicant', 'અરજદારનો મોબાઇલ નંબર ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (231, NULL, NULL, 'Contractor License', 'Email-id of the applicant', 'અરજદારનો ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (232, NULL, NULL, 'Contractor License', 'Office No. / Block No.', 'ઓફિસ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (233, NULL, NULL, 'Contractor License', 'Building Name', 'બિલ્ડિંગનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (234, NULL, NULL, 'Contractor License', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (235, NULL, NULL, 'Contractor License', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (236, NULL, NULL, 'Contractor License', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (237, NULL, NULL, 'Contractor License', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (238, NULL, NULL, 'Contractor License', 'Attach document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (239, NULL, NULL, 'Contractor License', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (240, NULL, NULL, 'Contractor License', 'Type Of Organization', 'સંસ્થાના પ્રકાર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (241, NULL, NULL, 'Contractor License', 'Partnership deed', 'ભાગીદારી ખત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (242, NULL, NULL, 'Contractor License', 'attach file', 'ફાઇલ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (243, NULL, NULL, 'Contractor License', 'Partnership', 'ભાગીદારી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (244, NULL, NULL, 'Contractor License', 'Name of Partner', 'પાર્ટનરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (245, NULL, NULL, 'Contractor License', 'Date of Birth', 'જન્મ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (246, NULL, NULL, 'Contractor License', 'Home Address', 'ઘરનું સરનામું');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (247, NULL, NULL, 'Contractor License', 'Date of birth proof', 'જન્મતારીખ ની સાબિતી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (248, NULL, NULL, 'Contractor License', 'Address proof', 'સરનામું ની સાબિતી ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (249, NULL, NULL, 'Contractor License', 'Is Contractor License Previously Granted', 'શું કોન્ટ્રાક્ટર લાઇસન્સ પહેલાં મંજૂર થયેલ છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (250, NULL, NULL, 'Contractor License', 'Click to add details', 'વિગતો ઉમેરવા માટે ક્લિક કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (251, NULL, NULL, 'Contractor License', 'Contractor License Number', 'કોન્ટ્રાક્ટર લાઈસન્સ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (252, NULL, NULL, 'Contractor License', 'Date Of Issue (contractor license)', 'કોન્ટ્રાક્ટર લાઈસન્સ કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (253, NULL, NULL, 'Contractor License', 'Name Of Supervisor', 'સુપરવાઇઝરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (254, NULL, NULL, 'Contractor License', 'Permit No. of Supervisor', 'સુપરવાઈઝર પરમિટ(પરવાનગી) નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (255, NULL, NULL, 'Contractor License', 'Date of issue Of Supervisor Permit', 'સુપરવાઈઝર પરમિટ કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (256, NULL, NULL, 'Contractor License', 'Date of birth of supervisor', 'સુપરવાઈઝર ની જન્મ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (257, NULL, NULL, 'Contractor License', 'Age (if age of supervisor is more than 70 years attach medical certificate of civil surgeon)', 'ઉંમર (જો સુપરવાઇઝરની ઉંમર 70 વર્ષથી વધુ હોય તો સિવિલ સર્જનના તબીબી પ્રમાણપત્ર જોડો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (258, NULL, NULL, 'Contractor License', 'Attach document regarding supervisor', 'સુપરવાઇઝર સંબંધિત દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (259, NULL, NULL, 'Contractor License', 'Attach address proof of supervisor', 'સુપરવાઇઝર ના સરનામાનો પુરાવો જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (260, NULL, NULL, 'Contractor License', 'Attach medical certificate of civil surgeon', 'સિવિલ સર્જન ના તબીબી પ્રમાણપત્ર જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (261, NULL, NULL, 'Contractor License', 'Last experience of supervisor with any other licensed contractor', 'સુપરવાઇઝર નો અન્ય કોઇ લાઇસન્સ કોન્ટ્રાક્ટર સાથે નો છેલો અનુભવ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (262, NULL, NULL, 'Contractor License', 'Name of contractor', 'કોન્ટ્રેક્ટર નું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (263, NULL, NULL, 'Contractor License', 'Contractor License No.', 'કોન્ટ્રેક્ટર નો લાઈસન્સ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (264, NULL, NULL, 'Contractor License', 'From (Date of starting)', 'પ્રતિ (શરૂઆતની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (265, NULL, NULL, 'Contractor License', 'To (Date of leaving)', 'માટે (છોડવાની તારીખ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (266, NULL, NULL, 'Contractor License', 'Attach document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (267, NULL, NULL, 'Contractor License', 'Form “I” verified by Electrical Inspector or his representative(All Pages)', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (268, NULL, NULL, 'Contractor License', 'Attach documents regarding contractor license', 'કોન્ટ્રાક્ટર લાયસન્સ સંબંધિત દસ્તાવેજો જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (269, NULL, NULL, 'Contractor License', 'Bank solvency certificate', 'બેન્ક સૉલ્વેન્સી સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (270, NULL, NULL, 'Contractor License', 'Download The specimen for solvency certificate', 'સૉલ્વેન્સી પ્રમાણપત્ર માટે નો નમૂનો ડાઉનલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (271, NULL, NULL, 'Contractor License', 'Download The Instrument Form from the link below', 'નીચેની લિંક પરથી સાધનો નું ફોર્મ ડાઉનલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (272, NULL, NULL, 'Contractor License', 'Details of instruments (please fill the editable PDF & attach it back)', 'સાધનોની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (273, NULL, NULL, 'Contractor License', 'Invoice of instruments', 'સાધનોની ઇન્વોઇસ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (274, NULL, NULL, 'Contractor License', 'Owners Declaration', 'માલિક નું ડિકલેરેશન');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (275, NULL, NULL, 'Contractor License', 'Declaration Of Supervisor', 'સુપરવાઇઝર નું ડિકલેરેશન');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (276, NULL, NULL, 'Contractor License', 'Appointment Letter (if owner is not supervisor)', 'નિમણૂંક પત્ર (જો માલિક સુપરવાઇઝર ના હોય તો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (277, NULL, NULL, 'Contractor License', 'Letter of declaration(if the owner & supervisor are the same person)', 'ડિકલેરેશન પત્ર(જો માલિક અને સુપરવાઇઝર એક જ વ્યક્તિ હોય તો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (278, NULL, NULL, 'Contractor License', 'Affidavit', 'એફિડેવિટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (279, NULL, NULL, 'Contractor License', 'Download The content of affidavit from the link below', 'નીચેની લિંક પરથી એફિડેવિટની લખાણ ડાઉનલોડ કરો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (280, NULL, NULL, 'Contractor License', 'Signature (of Properiter/Director/Partners)', 'હસ્તાક્ષર (માલિક / નિયામક / પાર્ટનર્સ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (281, NULL, NULL, 'Contractor License Renewal', 'Name of contractor', 'કોન્ટ્રાક્ટર નું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (282, NULL, NULL, 'Contractor License Renewal', 'Contractor License No.', 'કોન્ટ્રાક્ટર નું લાઇસન્સ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (283, NULL, NULL, 'Contractor License Renewal', 'Date of Issue of License', 'લાઇસન્સ કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (284, NULL, NULL, 'Contractor License Renewal', 'Expiry Date Of License', 'લાઈસન્સની સમાપ્તિ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (285, NULL, NULL, 'Contractor License Renewal', 'Attach documents', 'દસ્તાવેજો જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (286, NULL, NULL, 'Contractor License Renewal', 'Copy of Form “I” verified by Electrical Inspector or his representative(All Pages)', 'ઇલેક્ટ્રિકલ ઇન્સ્પેક્ટર અથવા તેના પ્રતિનિધિ દ્વારા ચકાસવામાં આવેલ ફોર્મ "I"(બધા પાના) ની નકલ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (287, NULL, NULL, 'Contractor License Renewal', 'Details of Supervisor working with firm', 'કંપની સાથે કામ કરતા સુપરવાઇઝરની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (288, NULL, NULL, 'Contractor License Renewal', 'Name of supervisor', 'સુપરવાઇઝરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (289, NULL, NULL, 'Contractor License Renewal', 'Date of birth of supervisor', 'સુપરવાઈઝર ની જન્મ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (290, NULL, NULL, 'Contractor License Renewal', 'Date of joining', 'જોડાયા ની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (291, NULL, NULL, 'Contractor License Renewal', 'Is the above mentioned supervisor still working with the firm ?', 'ઉપરોક્ત સૂચિત સુપરવાઇઝર હજુ પણ કંપની સાથે કામ કરે છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (292, NULL, NULL, 'Contractor License Renewal', 'Yes', 'હા');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (293, NULL, NULL, 'Contractor License Renewal', 'No (If ''''no" Details of new supervisor)', 'ના (જો ના હોય તો નવા સુપરવાઇઝર ની વિગતો ભરો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (294, NULL, NULL, 'Contractor License Renewal', 'Date of leaving of old supervisor', 'જુના સુપરવાઇઝર ને છોડવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (295, NULL, NULL, 'Contractor License Renewal', 'Details of new supervisor', 'નવા સુપરવાઇઝર ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (296, NULL, NULL, 'Contractor License Renewal', 'Name of supervisor', 'સુપરવાઇઝરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (297, NULL, NULL, 'Contractor License Renewal', 'Date of birth of supervisor', 'સુપરવાઈઝર ની જન્મ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (298, NULL, NULL, 'Contractor License Renewal', 'Date of joining', 'જોડાયા ની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (299, NULL, NULL, 'Contractor License Renewal', 'Is there any change in address ?', 'સરનામામાં કોઈ ફેરફાર છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (300, NULL, NULL, 'Contractor License Renewal', 'Yes( if "yes" please provide new address)', 'જો હા હોય તો કૃપયા કરી ને નવું સરનામાં આપો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (301, NULL, NULL, 'Contractor License Renewal', 'No', 'ના');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (302, NULL, NULL, 'Contractor License Renewal', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (303, NULL, NULL, 'Contractor License Renewal', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (304, NULL, NULL, 'Contractor License Renewal', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (305, NULL, NULL, 'Contractor License Renewal', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (306, NULL, NULL, 'Contractor License Renewal', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (307, NULL, NULL, 'Contractor License Renewal', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (308, NULL, NULL, 'Contractor License Renewal', 'Attach document(Address proof only to be given if changes of address)', 'દસ્તાવેજને જોડો (સરનામાં માં ફેરફાર હોય તો જ સરનામાં ની સાબિતી આપો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (309, NULL, NULL, 'Contractor License Renewal', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (310, NULL, NULL, 'Contractor License Renewal', 'Signature of owner', 'માલિકની હસ્તાક્ષર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (311, NULL, NULL, 'Duplicate Form', 'PERSONAL DETAILS', 'વ્યક્તિગત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (312, NULL, NULL, 'Duplicate Form', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (313, NULL, NULL, 'Duplicate Form', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (314, NULL, NULL, 'Duplicate Form', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (315, NULL, NULL, 'Duplicate Form', 'Applying for supervisor / wireman permit or exemption certificate or marksheet', 'સુપરવાઇઝર / વાયરમેન પરમિટ અથવા મુક્તિ પ્રમાણપત્ર અથવા માર્કશીટ માટેની અરજી કરવી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (316, NULL, NULL, 'Duplicate Form', 'Wireman Or Supervisor Permit No.', 'વાયરમેન અથવા સુપરવાઇઝર પરમિટ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (317, NULL, NULL, 'Duplicate Form', 'Date Of Issue Of Permit', 'પરમિટ(પરવાનગી) કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (318, NULL, NULL, 'Duplicate Form', 'Attach Copy of Permit', 'પરમિટ(પરવાનગી)ની નકલ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (319, NULL, NULL, 'Duplicate Form', 'Exam Roll No.', 'પરીક્ષા રોલ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (320, NULL, NULL, 'Duplicate Form', 'Exam Month and Year', 'પરીક્ષાનો મહિનો અને વર્ષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (321, NULL, NULL, 'Duplicate Form', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (322, NULL, NULL, 'Duplicate Form', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (323, NULL, NULL, 'Duplicate Form', 'Taluka Name', 'તાલુકા નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (324, NULL, NULL, 'Duplicate Form', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (325, NULL, NULL, 'Duplicate Form', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (326, NULL, NULL, 'Duplicate Form', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (327, NULL, NULL, 'Duplicate Form', 'Attach electricty bill for address pfroof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (328, NULL, NULL, 'Duplicate Form', 'Attach Passport size Photograph', 'પાસપોર્ટ સાઈઝ નો ફોટોગ્રાફ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (329, NULL, NULL, 'Duplicate Form', 'Attach Affidavit', 'એફિડેવિટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (330, NULL, NULL, 'Interstate Permit', 'PERSONAL DETAILS', 'વ્યક્તિગત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (331, NULL, NULL, 'Interstate Permit', 'Surname', 'અટક');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (332, NULL, NULL, 'Interstate Permit', 'First Name', 'પ્રથમ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (333, NULL, NULL, 'Interstate Permit', 'Father / Husband Or Middle Name', 'પિતા / પતિ અથવા મધ્ય નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (334, NULL, NULL, 'Interstate Permit', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (335, NULL, NULL, 'Interstate Permit', 'School leaving certificate or matriculation certificate', 'શાળા છોડયાં નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (336, NULL, NULL, 'Interstate Permit', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (337, NULL, NULL, 'Interstate Permit', 'Gender', 'જાતિ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (338, NULL, NULL, 'Interstate Permit', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (339, NULL, NULL, 'Interstate Permit', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (340, NULL, NULL, 'Interstate Permit', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (341, NULL, NULL, 'Interstate Permit', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (342, NULL, NULL, 'Interstate Permit', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (343, NULL, NULL, 'Interstate Permit', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (344, NULL, NULL, 'Interstate Permit', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (345, NULL, NULL, 'Interstate Permit', 'TEMPORARY ADDRESS (If the address is as above please don''t fill Temporary or correspondance address)', 'અસ્થાયી સરનામું (જો સરનામું ઉપર પ્રમાણે છે, તો કૃપા કરીને અસ્થાયી અથવા પત્રવ્યવહાર સરનામું ભરો નહીં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (346, NULL, NULL, 'Interstate Permit', 'House No. / Flat No. / Block No.', 'ગૃહ નં. / ફ્લેટ નંબર / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (347, NULL, NULL, 'Interstate Permit', 'Building Name / Apartment Name', 'બિલ્ડિંગ નામ / એપાર્ટમેન્ટ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (348, NULL, NULL, 'Interstate Permit', 'Taluka Name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (349, NULL, NULL, 'Interstate Permit', 'District Name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (350, NULL, NULL, 'Interstate Permit', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (351, NULL, NULL, 'Interstate Permit', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (352, NULL, NULL, 'Interstate Permit', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (353, NULL, NULL, 'Interstate Permit', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ અથવા
કોઈપણ સરકાર માન્ય ID ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (354, NULL, NULL, 'Interstate Permit', 'CONTACT DETAILS', 'સંપર્ક ની વિગતો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (355, NULL, NULL, 'Interstate Permit', 'Mobile No.', 'મોબાઇલ નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (356, NULL, NULL, 'Interstate Permit', 'Alternate Mobile No. (Optional)', 'વૈકલ્પિક મોબાઇલ નંબર (વૈકલ્પિક)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (357, NULL, NULL, 'Interstate Permit', 'Email Id Of The Applicant', 'અરજદારનું ઇમેઇલ આઈડી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (358, NULL, NULL, 'Interstate Permit', 'QUALIFICATION & PRESENT DESIGNATION', 'લાયકાત અને વર્તમાન હોદ્દો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (359, NULL, NULL, 'Interstate Permit', 'Permit No. Of Other State', 'અન્ય રાજ્યની પરવાનગી નંબર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (360, NULL, NULL, 'Interstate Permit', 'Year Of Passing Exam (if passed exam)', 'પાસિંગ પરીક્ષા વર્ષ (જો પાસ થયેલ પરીક્ષા)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (361, NULL, NULL, 'Interstate Permit', 'Date Of issue Of Permit', 'પરમિટ(પરવાનગી) કાઢી આપવાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (362, NULL, NULL, 'Interstate Permit', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (363, NULL, NULL, 'Interstate Permit', 'Attach Original Permit Copy', 'મૂળ પરમિટ(પરવાનગી) ની નકલ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (364, NULL, NULL, 'Interstate Permit', 'Attach Exemption Certificate Copy If taken Exemption', 'જો એક્ઝેમ્પ્શન લેવામાં આવેલ હોય તો એક્ઝેમ્પ્શન પ્રમાણપત્ર જોડો.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (365, NULL, NULL, 'Interstate Permit', 'Attach affidavit if Interstate', 'જો ઇન્ટરસ્ટેટ હોય તો એફિડેવિટ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (366, NULL, NULL, 'Interstate Permit', 'Name Of Present Organization In Gujarat', 'ગુજરાતમાં વર્તમાન સંગઠનનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (367, NULL, NULL, 'Interstate Permit', 'Address Of Present Organization In Gujarat', 'ગુજરાતમાં વર્તમાન સંગઠનનું સરનામું');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (368, NULL, NULL, 'Interstate Permit', 'Attach Appointment Letter', 'નિમણૂંક પત્ર જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (369, NULL, NULL, 'Interstate Permit', 'I hereby do solemnly declare that the particulars stated above are correct and true to best of my knowledge and i am not having any other permit of any state except stated above.', 'હું અહીંથી ગંભીરતાપૂર્વક જાહેર કરું છું કે ઉપરોક્ત વિગતો સાચી છે અને મારા જ્ઞાનના પ્રમાણે શ્રેષ્ઠ અને સાચી છે અને ઉપર જણાવેલી કોઈપણ રાજ્ય સિવાયની અન્ય કોઇ પરમિટ નથી.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (370, NULL, NULL, 'Repeater Candidate Examination', 'Name of Candidate', 'ઉમેદવારનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (371, NULL, NULL, 'Repeater Candidate Examination', 'Date Of Birth (As per school leaving certificate)', 'જન્મ તારીખ (શાળા છોડવાના પ્રમાણપત્ર મુજબ)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (372, NULL, NULL, 'Repeater Candidate Examination', 'Attach Document', 'દસ્તાવેજ જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (373, NULL, NULL, 'Repeater Candidate Examination', 'School leaving certificate or matriculation certificate', 'શાળા છોડયા નું પ્રમાણપત્ર અથવા મેટ્રિક સર્ટિફિકેટ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (374, NULL, NULL, 'Repeater Candidate Examination', 'Age', 'ઉંમર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (375, NULL, NULL, 'Repeater Candidate Examination', 'Exam Type', 'પરીક્ષાનો પ્રકાર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (376, NULL, NULL, 'Repeater Candidate Examination', 'EXAMINATION REQUIREMENTS (For Reappearing In Examination)', 'પરીક્ષાની આવશ્યકતા (પરીક્ષામાં ફરીથી હાજર થવા માટે)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (377, NULL, NULL, 'Repeater Candidate Examination', 'Previous Exam Roll No.', 'પહેલાનો પરીક્ષા નો રોલ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (378, NULL, NULL, 'Repeater Candidate Examination', 'Previous Exam Centre', 'અગાઉનું પરીક્ષા કેન્દ્ર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (379, NULL, NULL, 'Repeater Candidate Examination', 'Previous Exam Date/Month & Year', 'અગાઉનીપરીક્ષા તારીખ / મહિનો અને વર્ષ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (380, NULL, NULL, 'Repeater Candidate Examination', 'Preferred Examination Centre', 'મનપસંદ પરીક્ષા કેન્દ્ર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (381, NULL, NULL, 'Repeater Candidate Examination', 'Preferred Mode Of Language', 'ભાષાની મનપસંદ રીત');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (382, NULL, NULL, 'Repeater Candidate Examination', 'I hereby declare that particular stated above are correct and true to the best of my knowledge', 'હું અહીંથી જાહેર કરું છું કે ઉપર જણાવેલ ચોક્કસ માહિતી મારા જ્ઞાનના પ્રમાણે યોગ્ય અને સાચી છે');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (383, NULL, NULL, 'Repeater Candidate Examination', 'Photo', 'ફોટો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (384, NULL, NULL, 'Repeater Candidate Examination', 'Signature', 'હસ્તાક્ષર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (385, NULL, NULL, 'Interstate Renewal Supervisor', 'Name of applicant', 'અરજદારનુંં નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (386, NULL, NULL, 'Interstate Renewal Supervisor', 'Gujarat state Permit No.', 'ગુજરાત રાજ્ય પરમિટ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (387, NULL, NULL, 'Interstate Renewal Supervisor', 'Date of issue', 'કાઢી આપ્યા તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (388, NULL, NULL, 'Interstate Renewal Wireman', 'Name of applicant', 'અરજદારનુંં નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (389, NULL, NULL, 'Interstate Renewal Wireman', 'Gujarat state Permit No.', 'ગુજરાત રાજ્ય પરમિટ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (390, NULL, NULL, 'Interstate Renewal Wireman', 'Date of issue', 'કાઢી આપ્યા તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (391, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Is there any change or correction in name ?', 'શું નામમાં કોઈ ફેરફાર અથવા બદલાવ છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (392, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Name of contractor (In case of name change)', 'કોન્ટ્રાક્ટર નું નામ(જો નામ માં બદલાવ હોય તો)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (393, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Contractor license no.', 'કોન્ટ્રાક્ટર લાઇસન્સ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (394, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Date of issue of license', 'લાયસન્સ કાઢી આપ્યાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (395, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Is there any change in address ?', 'સરનામાંમાં કોઈ ફેરફાર છે?');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (396, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Office no. / block no.', 'ઓફિસ નં. / બ્લોક નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (397, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Building name', 'બિલ્ડિંગ નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (398, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'State', 'રાજ્ય');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (399, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'District name', 'જિલ્લાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (400, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Taluka name', 'તાલુકાનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (401, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Pincode', 'પીન કોડ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (402, NULL, NULL, 'MODIFICATION IN CONTRACTOR’S DETAILS', 'Attach electricty bill for address proof or any Govt. valid ID proof', 'સરનામાના પુરાવા માટે વીજળી બિલ જોડો અથવા કોઇ સરકાર માન્ય ઓળખ ની સાબિતી જોડો');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (403, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Name of contractor', 'કોન્ટ્રાક્ટરનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (404, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Contractor license no.', 'કોન્ટ્રાક્ટર લાઇસન્સ નં.');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (405, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Date of issue of license', 'લાયસન્સ કાઢી આપ્યાની તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (406, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Type of organization', 'સંસ્થાનો પ્રકાર');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (407, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Partnership deed (in case of change in partners)', 'ભાગીદારી ખત (ભાગીદારોમાં ફેરફારના કિસ્સામાં)');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (408, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Name of Partner', 'ભાગીદારનું નામ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (409, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Date of Birth', 'જન્મ તારીખ');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (410, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Home Address', 'ઘરનું સરનામું');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (411, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Date of birth proof', 'જન્મ તારીખ ની સાબિતી');
INSERT INTO "tempData" (id, key, lang, screen, fieldname, value) VALUES (412, NULL, NULL, 'MODIFICATION IN PROPRIETOR Or PARTNERS NAME', 'Address proof', 'સરનામું ની સાબિતી ');

